### ISSUE TITLE
Report 2 bugs and 1 improvement.

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#1010]
## 1. When you save or save as your project, the extension '.sb2' will disappear if filename is only 3 characters.
2 characters is ok:
![image](https://cloud.githubusercontent.com/assets/8316018/13040048/076dd694-d3e2-11e5-8014-a8a4e9e4b6f9.png)
![image](https://cloud.githubusercontent.com/assets/8316018/13040051/15da1e0e-d3e2-11e5-8268-8512ba52e243.png)
3 characters, no extension:
![image](https://cloud.githubusercontent.com/assets/8316018/13040055/23c878f8-d3e2-11e5-84e6-e1a582795db2.png)
![image](https://cloud.githubusercontent.com/assets/8316018/13040058/2907e7fe-d3e2-11e5-90e6-42cb3e9865bb.png)
4 characters is ok:
![image](https://cloud.githubusercontent.com/assets/8316018/13040066/3ef4f318-d3e2-11e5-809e-d2d6a13bfee2.png)
![image](https://cloud.githubusercontent.com/assets/8316018/13040069/440047ae-d3e2-11e5-95c3-30d8d1f4d105.png)

## 2. When the backdrops of stage is named by numbers, the block of 'switch backdrop to ..' doesn't work well, but backdrops of sprite is ok. I think the code forgets type conversion method like .toString().
![image](https://cloud.githubusercontent.com/assets/8316018/13039992/932b70ca-d3e1-11e5-9206-d377377aaa92.png)
![image](https://cloud.githubusercontent.com/assets/8316018/13040028/d5a8ace2-d3e1-11e5-9fa8-82572bafde76.png)

## 3. Scratch Timer is not accurate. 
Lots of teachers said sometimes the block of 'timer' can not meet their demand. The method of improvement is very simple, you can use the block of 'days since 2000'. Because this block get time from system function, it is accurate enough to meet any demand of timer.
I wrote a example on [https://scratch.mit.edu/projects/92505204/].

**Comment by TheLogFather** [comment]
There is no problem with the "timer" block in terms of its accuracy measuring time offset from starting the project. It uses the computer's time in just the same way as the "days since 2000" block, so there can be no errors there. (Though it does only give millisecond accuracy, whereas "days since 2000" gives better - but that isn't the main problem here...)

The main problem with your demo project is that you are multiplying by 10^5 for some reason. Why? If you multiply by the correct number of seconds in a day (86400) then you'll find they stay in sync rather better.

However, the way you're doing it, BOTH values are still slowly drifting from the correct timing, because of Scratch's 1/30th frame-rate. The "timer" method will drift a bit more quickly than "days since 2000" because it only gives values to a millisecond. That means your difference test of 0.1 is simply a bit less accurate for the "timer" block - but it's still not fully accurate for "days since 2000"!

For more info, and a suggestion about how you *should* be doing timing if you really want it to be accurate, see the comments I left on your project...

**Comment by TheLogFather** [comment]
For the backdrop issue, yes, Scratch can get confused if you use backdrops (or costumes) that have numerical values for names.

The problem is that Scratch tries very hard to 'hide' all the issues of variable 'type' from young Scratchers.

However, there are some places where it's really hard to know exactly what the intentions of the Scratcher are meant to be, so it makes some guesses, and sometimes they are wrong!

There is a way to get around it all by giving it a 'helping hand' to ensure it makes the choice you want (i.e. by ensuring it treats the backdrop/costume expression as either a string or numerical value via string operators like "join", or via mathematical operations that Scratch knows must give a number) - but the simplest workaround is simply to NOT use numerical values for backdrop/costume names! :)

**Comment by TheLogFather** [comment]
For the .sb2 extension issue, I couldn't really see the problem you talked about, though I expect things may well work in a different way for you if you're on Windows...?

I'm on a Mac, and when I save to disk it *only* includes the .sb2 extension in the filename if I explicitly include it myself.

**Comment by TheLogFather** [comment]
Actually, considering the backdrop issue, I think there is a case to be made that Scratch can make a better guess if the item has come from the dropdown menu rather than from an expression (containing variables/operators/etc.)

If the backdrop was simply chosen from the dropdown then it's quite clear that it should be treated as a string for a backdrop name, rather than potentially a numerical value.

I'll go take a look at the source and come up with a patch that fixes that...

**Comment by ntlrsk** [comment]
Backdrops are numbered in the backdrop editor (see attached), and can be referenced that way using variables or typing in numbers. So I think it's best practice when coding not to name them with integer numbers, and leave the code as is.

![image](https://cloud.githubusercontent.com/assets/4721032/13064334/b9724798-d41f-11e5-86f5-d55bfd4e0ae7.png)

**Comment by ntlrsk** [comment]
@lize777: Please post each topic as a separate github issue so that they can be addressed more clearly. Thank you.

**Comment by TheLogFather** [comment]
It's certainly 'best practice' not to use numerical values in backdrop/costume names.
But that won't stop it happening...

At the moment there's an inconsistency between costume names and backdrop names when chosen from their dropdown menus. A costume name that is numerical will switch correctly when chosen from the menu. A backdrop name will not.

The Scratch code needs fixing to make this behaviour consistent, and the most sensible choice is the way the costume menu behaves (since it correctly understands that the chosen name cannot possible be understood numerically).

**Comment by lize777** [comment]
@ntlrsk ok, wait

**Comment by lize777** [comment]
@ntlrsk I post each topic, close this issue.

**Comment by ntlrsk** [comment]
@TheLogFather Ah, thanks for explaining - I see now, that makes sense to make them consistent.  @lize777 thanks for posting the topics separately.
