### ISSUE TITLE
[BUG] When the backdrops of stage is named by numbers, the block of 'switch backdrop to ..' doesn't work well, but backdrops of sprite is ok. I think the code forgets type conversion method like .toString().

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#1013]
![image](https://cloud.githubusercontent.com/assets/8316018/13039992/932b70ca-d3e1-11e5-9206-d377377aaa92.png)
![image](https://cloud.githubusercontent.com/assets/8316018/13040028/d5a8ace2-d3e1-11e5-9fa8-82572bafde76.png)

Though @ntlrsk said that it is not a best practice, we can not assume user's behavior.

**Comment by TheLogFather** [comment]
Just to note the following patch fixes this issue, making "switch backdrop" behave in the same way as "switch costume" (well, almost**):
https://github.com/TheLogFather/scratch-flash/commit/382ffe9b7a320e291f15ba6378c41cc6f10728d6

** note that there is still a difference because of the "previous/next backdrop" choices existing in the "switch backdrop" menu, but the "previous/next costume" choices NOT existing in the "switch costume" menu, even though the code actually recognises them (see demo project [here](https://scratch.mit.edu/projects/69273706/)).

**Comment by cwillisf** [comment]
Resolved with #1029
