### ISSUE TITLE
README.md is out of date and missing some information

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-flash#1046]
The README.md file in this repository should be updated:
- It should suggest using Gradle instead of Ant in order to simplify the SDK setup process.
- It should explain the differences between scratch-flash and what's found on scratch.mit.edu .

**Comment by beardad1975** [comment]
It's a good idea.  Last week I followed the instructions in README. Using Ant to build SWF, I got nothing but errors. Then I saw [ the Article in Scratch Forum](https://scratch.mit.edu/discuss/topic/38970/) . By By using gradle ,  the SWF was built without problem. 

After building the SWF ,  I switched it with the one in Scratch2 folder . I noticed  that  it  is different than what I saw in Scratch offline editor.  All the media were missing.  I  don't know what is happening.

I thought this issue is a good suggesting to help a  scratch-flash newbie like me.
