### ISSUE TITLE
opening existing project with WeDo 2.0 blocks show as undefined

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1058]
Opening any of the starter WeDo 2.0 projects from the Scratch WeDo page shows the WeDo blocks as undefined:
![image](https://cloud.githubusercontent.com/assets/4721032/14140365/7f638c76-f646-11e5-9bd6-6c4763aadbaf.png)

**Comment by ntlrsk** [comment]
I'm still seeing these as undefined - clicking that same project from the WeDo page

**Comment by cwillisf** [comment]
I took a look at the project JSON and it looks like the project was somehow saved incorrectly: the project doesn't contain a `savedExtensions` section at all. It's possible that this happened because the projects were saved before the WeDo 2.0 extension was added as an "official" extension.

It should work to load the project, add the WeDo 2.0 extension, and save the project again using the "scratch-legowedo" user.

**Comment by ntlrsk** [comment]
Thanks, now fixed!
