### ISSUE TITLE
(1 / 0) returns "Infinity".

### ISSUE THREAD

**Issue by abee2** [LLK/scratch-flash#1060]
Any division expressions where the divisor is zero must return "divide by zero" error.
However Scratch returns "Infinity" for those expressions.
Scratch 1.4 returns the error in those case correctly.
It is difficult to accept for educational purpose.
One Japanese kid said "(1 / 0) is Infinity, because Scratch answered that.".

**Comment by bjskistad** [comment]
Yeah. I agree, they should change that. Make a PR?

**Comment by liam4** [comment]
There's an issue with throwing an error, though. Assuming that the error stops the script and/or program, many old programs would be broken - what if an old program would divide by 0 and not have an issue with that? The program will crash/stop/break because of the divide by zero error..

**Comment by TheLogFather** [comment]
It seems to be 'feature' of Scratch that it doesn't report any 'errors' at all, ever – nothing shall stop these scripts from ploughing on! ;)

There are numerous cases where Scratch will ignore far more blatant mistakes (out of range list item, out of range "letter of" position, non-existent costume, non-existent sound, non-existent variable in blue "_ of _" sensor block, motion/looks/pen/clone blocks used in stage, calling an undefined custom block, etc.)

Besides, 1/0 is not technically an error, though it is clearly highly likely that the user got something wrong somewhere, since the vast majority of Scratch users are really not going to be using ±Infinity.

However, there are times when I've actually *intended* to get Infinity in a Scratch project – and don't think for a moment that all languages will report this particular thing as a runtime error...

**Comment by abee2** [comment]
I think we need to define the context of this subject.
I know Scratch 2.0 (ActionScript) uses IEEE 754 for floating-point computation. This choice is reasonable for engineering purpose.
In other hand, Scratch is an educational programming language. Scratch is a successor of LOGO. And LOGO was made for learning mathematics through the microworld by Seymour Papert.
So I would like to discuss this subject as a context of mathematics.

**Comment by TheLogFather** [comment]
In mathematics we have no problem with division (of a non-zero number) by zero. It's only when used in computers that we assume there was (potentially) a mistake.

If you really want to find something that causes some trouble in mathematics, then the various indeterminate forms are the ones to watch for (e.g. zero divided by zero, infinity minus infinity, zero to the power zero, etc.)

TBH, if Scratch was to be changed so it started to report errors, I'd much rather it first started to report *real* errors (like the ones I mentioned above) rather than *potential* errors like division by zero.

**Comment by abee2** [comment]
In algebra, division by zero is undefined. It is never calculated. The value is not infinity. It is just meaningless.
I still think Scratch should raise an error for this expression. However, I understood that it requires a new error handling mechanism.
So I propose to add a new item to the FAQ about Scratch's calculation policy by IEEE 754 for the avoidance of confusion.

**Comment by thisandagain** [comment]
@abee2 Thanks for the feedback. I'll try to address each individual point here as best I can.

> Any division expressions where the divisor is zero must return "divide by zero" error.

It is a feature of some programming languages (like Python and Go) to return a "Division By Zero" error when dividing a floating point number by zero. However, many others languages including: C, JavaScript, Ruby, Julia, and Java all return `Infinity` as is expected for languages that follow the [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point) specification for Floating Point Arithmetic.

> Scratch 1.4 returns the error in those case correctly.

It's hard to say what is "correct" in this instance, but it is great to point out an important inconsistency between 1.4 and 2.0 which is related to Scratch 2.0's underlying use of [ActionScript 3.0's Number data type](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Number.html) as well as Scratch 2.0's design decision to not present errors to the user.

> It is difficult to accept for educational purpose. One Japanese kid said "(1 / 0) is Infinity, because Scratch answered that.".

While I absolutely love kids using Scratch to help them with their math homework, I tend to agree with you that the behavior demonstrated in the IEEE specification runs contrary to common arithmetic which is likely a more common starting point for the majority of Scratchers.

> There's an issue with throwing an error, though. Assuming that the error stops the script and/or program, many old programs would be broken - what if an old program would divide by 0 and not have an issue with that? The program will crash/stop/break because of the divide by zero error.

I agree with @liam4's point here. I don't think throwing an error is the correct behavior for Scratch in addition to its high potential for disrupting existing projects. Rather, I think what is likely more appropriate may be to return `Undefined`. I think we should be clear however that this still would be a breaking change, as @TheLogFather points out there are times when users are intentionally or unintentionally using `±Infinity` as a byproduct of division by zero. That said, the scale of that use case is a little unclear to me. I'll try to to see if we can use some of our research tools to get better sense. @Paddle2See may have some intuitions here too.

> Scratch is an educational programming language. Scratch is a successor of LOGO. And LOGO was made for learning mathematics through the microworld by Seymour Papert. So I would like to discuss this subject as a context of mathematics.

You are correct. Scratch has been heavily influenced by LOGO and the work of Seymour Papert. That said, Scratch's objectives extend beyond "learning mathematics" into many dimensions of learning including computational thinking, design, creativity, invention, and community. This can make design decisions like this a little less clear, but ultimately I think this means that we end up building an experience that is inclusive of the great diversity of interests and intentions that children bring to Scratch.

/cc @ntlrsk @cwillisf

**Comment by TheLogFather** [comment]
Some time ago I actually made a start on an error messaging system for Scratch.

It was based, in part, on the coding I did for the block search & highlighting in #861.

What would happen was (well, I was getting to the point of making it happen, but it was nowhere near ready, and many things have changed within the Scratch code since then) that if it came across an error while playing a project *in the editor*, then it would pause the project, highlight the bad block in red, and show a message that described the problem (e.g. "list index too large", "list index less than one", "unknown costume name / number", "expression is not a numerical value", etc.)

The idea was then to give the user the option of stopping the project, continuing the project (but still reporting the error if it happens there again), or ignoring that error for that block in future.

If the project was not played in the editor, then it would still ignore all errors as it does now.

One of the issues I had with it was that last option... Unfortunately, I can imagine many Scratchers just choosing that option to get rid of the message, and then never getting around to investigating the real problem because they never see that message again. However, that option also does need to be there, since there are cases where the user really *intends* something like an invalid costume name for a specific purpose (e.g. case detection).

One way around the above dilemma would be for it to ignore that error from then on only in the current session – the message would appear again after next reload. Another way would be for it to still highlight the bad blocks in red, but not pause the project – but you would be able to get at the error message from a right-click drop-down menu item. (Actually, perhaps that last idea could even be the default way it works?)

Thoughts...?

**Comment by TheLogFather** [comment]
Oh, yeah, I forgot to also say another feature I was planning for it...

Even if the project was not played in the editor (i.e. it was played in the normal project view, or fullscreen), once you do "see inside", it would still have blocks highlighted in red which had caused an error while it was playing.

While viewing a played project with errors highlighted in the editor (whether due to previously playing not in editor, as above, or because you ignored them while playing in editor), you can then cycle through the highlighted blocks by using a little widget just like the one in my search & highlight #861, and so more easily find out what the errors were.

**Comment by TheLogFather** [comment]
Hmmm, re-reading what I wrote above, I realised it didn't properly explain how I related it to the original suggestion (though maybe it was reasonably obvious?)

Essentially, I wouldn't want to see Scratch stop a running project for this error UNLESS it was part of a wider error message mechanism, and which only stops the project while in the editor, *and* includes the ability to ignore specific errors (at least temporarily, for a project load session).
