### ISSUE TITLE
[IDEA] Better way of rendering color effect for vector

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-flash#1076]
I have an idea for a better way to render the color effect for vector sprites.

Currently (as far as I know) the color effect changes the color pixel-by-pixel. This method is incredibly laggy when overused.

However, since vector is made of objects, not pixels, the color effect could simply change the hue value of each object, rather than going through several hundred or even thousand pixels.

This would make it much easier to use the color effect with vector, although I'm not exactly sure how the color effect is handled or if changing values of individual objects is even possible.

**Comment by TheLogFather** [comment]
The colour effect shouldn't be too laggy unless your OS/browser/Flash/GPU is, for some reason, failing to allow Stage3D mode for the player. I've noticed quite a few Windows users seem to suffer from that when using certain browsers (Chrome?), even with everything up to date and on quite recent hardware, which seems a bit odd.

If you don't have Stage3D capability then colour effect will be extremely slow (as will many other effects).
You can check for Stage3D using this project: https://scratch.mit.edu/projects/89629434/ (It'll start off with Stage3D OFF, but hit ctrl-M, or cmd-shift-M on Mac, to toggle it ON. If it won't switch on then that's why colour effect is so laggy for you...)

I think it'd be a good idea to apply colour effect to vector costumes in the way you suggest for the NON-Stage3D case, though. That would probably help performance in the majority of cases. The main issue I can see at the moment would be how it interacts with ghost effect (which already behaves in an unexpected way for multiple overlapping objects of a vector costume when Stage3D is off).
