### ISSUE TITLE
[Microworlds] Add ability to open code from an embedded project in Scratch editor

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1077]
For the microworlds project, we want to be able to open the code from an embedded project within the Scratch editor. 

Here's an example of an embedded project:
https://scratch.mit.edu/pathways/hiphop

After the Scratcher plays with the code, we'd like them to be able to click a button to open it in the Scratch editor. 

(The sprites are already assets on the server. Ideally their position would be saved too, but not essential.)

**Comment by TheLogFather** [comment]
Somewhat offtopic, and just curious, but I noticed that it switches into Stage3D mode with all effects, including brightness & ghost (unlike the standard player, which only switches with all but these two).
Is this intentional? If not, any idea why it would end up different?

**Comment by bsb20** [comment]
Due to the cross-cutting nature of this change, there are 3 PR's in question to add the feature they are as follows:

[scratch-flash 1116](https://github.com/LLK/scratch-flash/pull/1116):
The actual function calls from the editor to javascript to trigger a project remix when appropriate

[scratch-flash-online 273](https://github.com/LLK/scratch-flash-online/pull/273):
The interface modifications, nicely segregated into the online-only subclass of the UI "part" that was changed

[scratchr2 3640](https://github.com/LLK/scratchr2/pull/3640):
Making sure proper functionality is available from the "pathways" pages, and exposing the necessary function calls to a .swf embeded in an iframe.

**Comment by bsb20** [comment]
Some follow up things are also in [scratchr2 3663] (https://github.com/LLK/scratchr2/pull/3663)
