### ISSUE TITLE
Scripts tab > Events > "When backdrop switches" block extends out of view

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1080]
When you create a new project, in the Scripts tab under the Events section, the block "when backdrop switches to [backdrop1]" is larger than the width of the tab, causing the right side of the block to be hidden from view. There is no scroll bar for the tab. I maximized my window to make sure it was larger than the minimum supported screen-size.

Browser:
Noticed in Chrome Version 49.0.2623.112 (64-bit)
Also exists in Safari 9.1 (11601.5.17.1)

Scratch version: v445.2
scratch-flash: 2a019c6
scratch-flash-online: 015f4cc

Priority: this does not block any functionality, as you can drag the block to the script area to see what it says (and to use it). This is just a minor aesthetic issue, I would think very low priority.

<img width="1274" alt="screen shot 2016-04-14 at 4 45 34 pm" src="https://cloud.githubusercontent.com/assets/1320456/14543562/c3d2ce3a-0262-11e6-9532-e10b52231c04.png">

**Comment by cpseager** [comment]
Related to #742

**Comment by TheLogFather** [comment]
Just to note that you can actually scroll that block palette pane (though that can kinda cause its own issues sometimes...) by using the scroll-wheel with shift held down.
(But note that it doesn't work in all browsers, in which case you can drag a block to the right/left edge of the pane, and it'll scroll).

**Comment by TheLogFather** [comment]
Wut...? I'm confused...

How does #744 fix this? Isn't the (cosmetic) issue with this simply that the pane is not wide enough to fit this long block? How does preventing the pane from scrolling 'fix' this? (Allowing it to scroll, as it does right now, means that you ARE able to see the right side of the block, even if in a not particularly great way...)

The problem is way worse for long custom blocks, and not being able to scroll means you can no longer get to see which block is which (if you have several that are the same at the start), unless you actually grab it and drag it out.

Am I missing something of what #744 does...?

**Comment by jwzimmer** [comment]
I think this issue may be related to #616, "blocks palette width scaling".

**Comment by cwillisf** [comment]
I agree with @TheLogFather that #744 doesn't really address this issue, so I'm removing the "has-patch" label here. IMO this issue is basically "some blocks cause the need to scroll" whereas #742 was "sometimes the palette scrolls when you don't want it to scroll"

**Comment by cwillisf** [comment]
From @TheLogFather on #744:
> However, shift-scroll appears to work only on certain browsers (works on FF, but not Safari for me).
> 
> That's why I suggested the 'snap back' as a potential alternative temporary 'band-aid' fix for the accidental scrolling 'surprise' – yes, the scroll 'surprise' still happens during the drag, but its effects are immediately mitigated on drop.

I think the 'snap back' idea is a promising one but I'm afraid I don't have time to implement it right now. If you (@TheLogFather) would like to give it a go you're more than welcome! It wouldn't surprise me if the solution to this issue (#1080 I mean) -- 'snap back' or otherwise -- involves reverting #744 as part of a larger whole, but in the absence of a more complete solution I think #744 is good for most users for now.
