### ISSUE TITLE
Projects stuck on 100% of assets loaded; can't "see inside" them

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1085]
Two users have sent issues to freshdesk saying they cannot load their projects. The projects show the assets being loaded, and eventually all are loading according to the progress bar/ UI, but the project seems to hang there. You cannot load it in the editor via My Stuff or "See Inside" button. The project does not play.

User 1:
- Project ID: 105311331
- Operating System: MacOS Macintosh X 10.10.5 
- Browser: Chrome 49.0.2623.112 
- Flash Version: Flash 21.0 (release 0)

User 2:
- Project ID: 104012599 
- Operating System: Windows NT 10.0 
- Browser: Chrome 49.0.2623.112 
- Flash Version: Flash 21.0 (release 0)

I could not load the projects, either. To reproduce, just go to the project ID using the Scratch URL.
<img width="592" alt="screen shot 2016-04-21 at 11 39 43 am" src="https://cloud.githubusercontent.com/assets/1320456/14715156/c920d636-07b5-11e6-9aa5-35a802288bbb.png">

scratch v445.2
scratch-flash 2a019c6
scratch-flash-online 015f4cc
Browser: Chrome 50.0.2661.75 (64-bit)

**Comment by cwillisf** [comment]
I'm still working on the details, but it looks like what's happening is that the project contains at least one costume which Scratch can't load. . Unfortunately, the code that's supposed to report that error is instead suppressing it.

Worse yet, as soon as one error is encountered the rest of the files in that sprite are skipped in such a way that `decodeAllImages()` is still expecting results for those files. This leads to the "stuck" behavior described in the issue report.

We should improve the way that `decodeAllImages()` tracks progress in addition to handling these errors more gracefully. Since we may in theory have many errors due to one project-load, we may want to aggregate those error reports in a single dialog at the end of the load.

**Comment by jwzimmer** [comment]
Another user reported this issue with project 106997819.

**Comment by Choco31415** [comment]
If it helps, I found another Scratcher report this bug. The project is unshared, but hopefully ST/moderators should still be able to see it.

Project ID: 100897251
Operating System: Windows NT 10.0
Browser: Chrome 49.0.2623.87
Flash Version: Flash 21.0 (release 0)

The repot was posted on April 1st, 2016.

**Comment by cwillisf** [comment]
Each of these projects contains a costume or backdrop that fails to load correctly.

I put together a fix for the fact that bad costumes cause the overall project load to fail in a bad way, but I'd be interested to hear if anyone can cause a costume or backdrop to become corrupt in this way.

It's possible that it's not a bug in our code, but I'm not ready to rule that out yet :)
