### ISSUE TITLE
Chinese tips window showing Spanish images

### ISSUE THREAD

**Issue by gunchleoc** [LLK/scratch-flash#1086]
Reported on the forum:

> Anyone from Scratch team can help to restore the untranslated images to English?
>
> I suspect there's very few Chinese scratchers can read Spanish.

https://scratch.mit.edu/discuss/topic/194838/

**Comment by jwzimmer** [comment]
As far as I can tell, there are two Chinese-language options for Scratch, 我的東西 and 我的项目中心. I do not see any Spanish text in the tips area (in the online editor, click the question mark icon at the far right to expand the tips window) when I choose either Chinese-language option.

**Comment by jwzimmer** [comment]
(Note: The two sets of Chinese-language characters in my above comment are the way "My Stuff" is translated when you choose either of the two Chinese-language options, not that names of the Chinese-language options themselves.)

**Comment by ntlrsk** [comment]
Here's an example:
![image](https://cloud.githubusercontent.com/assets/4721032/14924367/25d10508-0e10-11e6-880f-34fbf8cbb74b.png)

**Comment by ntlrsk** [comment]
Here's another example of Spanish images in Chinese tips window (Getting Started first page):
![image](https://cloud.githubusercontent.com/assets/4721032/14924418/711d08fe-0e10-11e6-96b1-c9a1491dfc06.png)

**Comment by jwzimmer** [comment]
@ntlrsk Awesome, thank you so much. (I should make my comments clearer, though, as I had not given up on repro'ing this issue yet, just making note of what I had seen so far! : ) )

**Comment by jwzimmer** [comment]
Steps to repro:
- Go to scratch.mit.edu
- Click on My Stuff from the dropdown at upper right
- Scroll to the bottom of My Stuff
- Change the language selection to one of the Chinese-language options (there are two)
- Click on one of your projects
- Use See Inside to get to the editor
- Click on the question mark icon at the far right
- Click Getting Started with Scratch (top tutorial/ tip option)
- Click Begin (upper right within the tip window)
- Note that the blocks in the gif are in Spanish ("Movimiento", "mover").

There are several places where Spanish images are used if you check out the various tip/ tutorial sections. I did not see any Spanish images getting loaded when the chosen language was English.

**Comment by mewtaylor** [comment]
@ntlrsk @jwzimmer  – just took a look, and I can no longer repro this. I'm wondering if it was a caching issue that has since expired...

**Comment by jwzimmer** [comment]
@mewtaylor I'm still seeing this on production, but just with images and not with gifs anymore. I followed my repro steps in the prior comment. 
I also noticed that the non-English, non-Chinese text I'm seeing here seems to be French instead of Spanish?
<img width="249" alt="screen shot 2016-08-17 at 3 56 46 pm" src="https://cloud.githubusercontent.com/assets/1320456/17751025/3b23dc6c-6493-11e6-94d8-aaeec14f33e1.png">
<img width="335" alt="screen shot 2016-08-17 at 3 53 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/17750921/d15950aa-6492-11e6-9186-a29ebf548730.png">
<img width="343" alt="screen shot 2016-08-17 at 3 52 47 pm" src="https://cloud.githubusercontent.com/assets/1320456/17750922/d15c9e04-6492-11e6-8ee8-0f965d11b1ac.png">
<img width="331" alt="screen shot 2016-08-17 at 3 54 43 pm" src="https://cloud.githubusercontent.com/assets/1320456/17750958/f3a019d2-6492-11e6-817b-756e36e84d0e.png">
<img width="320" alt="screen shot 2016-08-17 at 3 55 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/17750991/0e718138-6493-11e6-9527-c2465e497a9a.png">
<img width="315" alt="screen shot 2016-08-17 at 3 55 16 pm" src="https://cloud.githubusercontent.com/assets/1320456/17750992/0e71d0c0-6493-11e6-8e4b-1f5ef85b2545.png">
