### ISSUE TITLE
Go In front of / behind [sprite name]

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#1095]
It might be nice to have blocks that take the guesswork out of ordering sprites.

```
Go in front of [sprite name]
Go behind [sprite name]
```

There is of course the complexity of clones to consider, but it could work either by just applying to the original sprite (like referencing variables of other sprites do), or it could take the set of all such sprites and move behind or infront of them all.

Another potentially useful addition would be to be able to query ones own depth... I assume it would be called 'layer #' in scratch language?

```
set var [my depth] = (layer #)
```

**Comment by TheLogFather** [comment]
Yes, layering could really do with some way to make it rather more useful, and this kind of thing has been suggested many times before in the forums, of course.

I think there are slight questions over the exact meaning of the first two blocks, and so how they behave – and you highlighted one of them already (clones, etc.)

Another example: does "go behind X" mean that it should place the sprite/clone so it's exactly one layer below X? (That's what I assume you mean, and probably how the vast majority of regular coders would understand it.) Or does it just mean that if it _isn't already_ somewhere behind X then it should go there?
(–presumably just one layer below X, though again, that's not explicit in the text.)
Similarly for "go in front of X".

I'm just wondering if some might interpret it the second way?

----

There's bound to be some confusion over what the "layer #" means – numerous times I've seen projects which imply the creator thinks of the layer number as rather like a depth position in space, and so the "go back" block is just changing that depth, essentially placing the object at a new depth from which it will not move until using the block again.

I don't really know how to avoid that confusion, and it's already prevalent, so I'm not sure that "layer #" would make it worse. (It may even help, as Scratchers start using it, and have to have it explained that it doesn't work as a fixed depth value...?)

----

Still, all of that doesn't detract from how useful this could be – and maybe someone can come up with more definitive ways to express the text of the blocks?

TBH, though, I think just having "layer #" would give everything you could want – that alone would be enough to implement your own "go in front of X" and "go behind X", including handling of clones.

**Comment by griffpatch** [comment]
>
> Yes, layering could really do with some way to make it rather more useful,
> and this kind of thing has been suggested many times before in the forums,
> of course.
>
> I think there are slight questions over the exact meaning of the first two
> blocks, and so how they behave – and you highlighted one of them already
> (clones, etc.)
>
> Another example: does "go behind X" mean that it should place the
> sprite/clone so it's exactly one layer below X? (That's what I assume you
> mean, and probably how the vast majority of regular coders would understand
> it.) Or does it just mean that if it *isn't already* somewhere behind X
> then it should go there?
> (–presumably just one layer below X, though again, that's not explicit in
> the text.)
> Similarly for "go in front of X".
>
> I'm just wondering if some might interpret it the second way?
>
Nope, the first interpretation is correct. Move the sprite to a depth 1
below the named sprite, or one above the named sprite is how I could see it
working, but I understand what you are saying.


> ------------------------------
>
> There's bound to be some confusion over what the "layer #" means –
> numerous times I've seen projects which imply the creator thinks of the
> layer number as rather like a depth position in space, and so the "go back"
> block is just changing that depth, essentially placing the object at a new
> depth from which it will not move until using the block again.
>
> I don't really know how to avoid that confusion, and it's already
> prevalent, so I'm not sure that "layer #" would make it worse. (It may even
> help, as Scratchers start using it, and have to have it explained that it
> doesn't work as a fixed depth value...?)
>
I think it would help, and would be quite a fun think to be able to access
and play with.


> ------------------------------
>
> Still, all of that doesn't detract from how useful this could be – and
> maybe someone can come up with more definitive ways to express the text of
> the blocks?
>
> TBH, though, I think just having "layer #" would give everything you could
> want – that alone would be enough to implement your own "go in front of X"
> and "go behind X", including handling of clones.
>
You have got a point there, although I'd prefer to have access to the in
front of block, or we might otherwise need to add a (layer # of [sprite
name]) sensing block adding... but it  might not be as powerful or
intuitive way of working.

**Comment by TheLogFather** [comment]
Yes, the first interpretation is clearly the only one that's unambiguous. The other gives too much ambiguity, so couldn't possibly be the sensible way to interpret the blocks. Was just meaning that *we* would see that as obvious due to being such oldies with decades of experience. But others may not. (Again, that doesn't necessarily mean it shouldn't happen – just something to bear in mind, and maybe see if there's another way to 'name' them.)

There's no need for a block for "layer # of sprite" – would simply add "layer #" to the left menu in the existing (_ of _) sensor block, which would be straightforward if a sprite already has a "layer #" concept to work with.

Yes, I think having the first two blocks is way more intuitive and immediately powerful, once the meaning is clear. (And, again, since the layering system is already so misinterpreted by many, I think even such potential slight, temporary confusion isn't really any worse – so I'm probably just causing trouble for no good reason, as usual...)

**Comment by Airhogs777** [comment]
I like the idea of (layer #) and ([layer @ v] of [sprite v]). They might benefit from a "go to layer ()" block as well. That would simplify some calculations we have to do for "go back () layers"

If the user is allowed to see what layer a sprite is on, I can see confusion arising from the mutability. For example, a user moves a sprite forward and is confused because the layer number is one lower than where it was moved in order to to compensate for its previous layer not existing anymore.
