### ISSUE TITLE
Double-clicking in Sound Library clicks through to the Stage 

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1100]
Double-clicking in the Sound Library clicks through to the Stage - this can switch which sprite is selected -- which is problematic.  (We saw this happen with kids in the music workshop on Saturday.)

To reproduce - try a project with a big sprite this: https://scratch.mit.edu/projects/107873291/#editor

1. Choose the saxophone sprite.
2. Open the Sound Library
3. Double-click the 'Music Loops' category
4. Click OK (or Cancel)
5. The cat sprite will be selected instead of the Sax (because it is underneath the area clicked in the library).

**Comment by ntlrsk** [comment]
Similar to this previous issue: https://github.com/LLK/scratch-flash/issues/554

**Comment by thisandagain** [comment]
Assigning to @jwzimmer for repro / connection to other issues.

**Comment by jwzimmer** [comment]
I can repro this following @ntlrsk's instructions. The cat sprite will be the active sprite instead of the saxophone, which would be pretty confusing, especially since you might not immediately notice what had changed. 
Note that the selected/ active sprite only changes if you *double-click* in the sound library. A single-click will not have any effect on the sprites.
I cannot repro the issue in #554, so that does seem to have been (stayed) fixed by #556. I'm not sure if the same approach taken in #556 could be used to fix this issue. (Also, I don't think this case is related to the issue I initially thought it might be related to.)

Browser: Chrome Version 50.0.2661.94 (64-bit)
Online editor v446
scratch-flash: 3ed8b52
scratch-flash-online: 10bddb1

I can also repro this behaviour in:
Safari Version 9.1 (11601.5.17.1)
Firefox 46.0

**Comment by cwillisf** [comment]
Looks like this happens with all media libraries. Updating @ntlrsk's steps:

1. Choose the saxophone sprite.
2. Open the Sound, Costume, or Backdrop Library
3. Double-click the 'Music Loops' category in the Sound Library, or the 'Castle' theme in the Costume or Backdrop Library.
4. Click OK (or Cancel)
5. The cat sprite will be selected instead of the Sax (because it is underneath the area clicked in the library).
