### ISSUE TITLE
when pulling global variable in from backpack it becomes a local variable

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1114]
When pulling a global variable in from the backpack it becomes a local variable in the project.

To reproduce:
1. - Make a global variable, put one of the variable blocks in the backpack
2. - Open another project - pull the block out of the backpack into the cat (or other sprite)
3. - Click the variable block - a local rather than global variable is created.

**Comment by Airhogs777** [comment]
It would be nice if a new cloudvar was generated, or if Scratch removed the cloud icon to avoid confusion

**Comment by ntlrsk** [comment]
Just to clarify - the issue I posted is not for cloud variables - so that would be best as a separate issue.

**Comment by Airhogs777** [comment]
Oh whoops, I misread the whole thing. Nvm

Still support tho

**Comment by TheLogFather** [comment]
This is a problem which turns up fairly often – for example, also when loading a whole sprite into a project from disk or backpack.

Whenever Scratch comes across a variable/list that it doesn't already know about, while running a script in a sprite/clone, it always creates that var/list as 'this sprite only'. This is because of its regular use of "lookupOrCreateVar/List", e.g. for the block "set var to": https://github.com/LLK/scratch-flash/blob/5cff62b909856b7d7b3d116a5dcc2b4f03de8482/src/scratch/ScratchObj.as#L430-L434

It may be worth noting that the converse case is also possible: if the *Stage* is running a script with a var/list that it doesn't recognise, then it gets created *global* – and that can cause a degree of chaos for a sprite which already has such a variable/list.
