### ISSUE TITLE
Support non-latin characters in the Paint Editor

### ISSUE THREAD

**Issue by gg23** [LLK/scratch-flash#1118]
hi,
I would like to create some scratch interactives for my Greek School kids and need to be able to display greek characters. Why is this not possible?

Thanks
Greg

**Comment by ntlrsk** [comment]
Hi @gg23 - unfortunately, the Scratch 2.0 paint editor does not support non-English characters due to a variety of size, time, and resource constraints (https://github.com/LLK/scratch-flash/issues/231) We're really sorry there isn't support for this in the current version. Our engineers have begun work on the next generation of Scratch, which should not have this limitation! 

A couple of workarounds for the current version of Scratch: (1) you can input Greek characters into the "say" block. (2) you can use the paint editor in Scratch 1.4 to create sprites in Greek, and then Share or upload them to the Scratch website. They will then be available as bitmap images.
