### ISSUE TITLE
No link to 'Join Scratch' in online editor

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-flash#1120]
It may help to retain newcomers to Scratch if we added the words "Join Scratch" in the project editor - next to the words "Sign in". 

It is possible to get to "Join Scratch" from the "Sign in" dialog but it is small and not obvious to click if you don't have an account. 

![image](https://cloud.githubusercontent.com/assets/4721032/15751375/e31cc112-28b7-11e6-87b2-3f4da488b65e.png)

**Comment by ntlrsk** [comment]
Or change the current wording to "Join or Sign in" (would need to alert translators)

**Comment by ntlrsk** [comment]
Another idea would be to revise this so the "Join Scratch" option is more visible in the dialog box:
![image](https://cloud.githubusercontent.com/assets/4721032/17976554/00a0debc-6abc-11e6-9d01-aa1c0f5e8cc7.png)

**Comment by ntlrsk** [comment]
@carljbowman @kaschm @thisandagain Wondering if we could make a more visible way to join Scratch in the editor before December influx of newcomers.

**Comment by cwillisf** [comment]
@carljbowman do you have opinions on which of these things we should work on?

I think it makes sense to both change the "Sign in" button/menu to say "Join or Sign in" (or maybe "Join Scratch or Sign in"? "Join Scratch or Sign In"?) **and** make the "Or Join Scratch" more prominently featured in the "Sign in" dialog. Do you think we need to change the layout of the "Sign in" dialog significantly in order to make the "join" option more noticeable?

For reference, the "Sign in" button/menu is implemented in the SWF, and the "Sign in" dialog is [`templates/modal-login.html`](https://github.com/LLK/scratchr2/blob/develop/templates/modal-login.html).

**Comment by carljbowman** [comment]
@cwillisf @ntlrsk - My recommendation would be to include 'Join Scratch' next to 'Sign In' within the Editor's Toolbar, rather than adding a link in the Sign In Dialog. 

<img width="300px" src="https://cloud.githubusercontent.com/assets/3409578/20006266/316359b0-a26d-11e6-962c-fe88e671a018.jpg">

Another version when a user is on a project page. 

<img width="300px" src="https://cloud.githubusercontent.com/assets/3409578/20006373/9b76c594-a26d-11e6-917d-dd05d924c4c1.jpg">

This area becomes pretty cluttered as we start to add more options, which is one concern if we were to make the 'Join Scratch' more prominent.

Thoughts?

**Comment by ntlrsk** [comment]
I think it's good to have the way you've laid out. Since the Remix and See project page buttons are colorful, I think they still stand out the most, so that's good.

**Comment by cwillisf** [comment]
Yeah, I think that makes sense too. Do you think we should change the "Sign in" dialog at all?

**Comment by carljbowman** [comment]
@cwillisf - Sorry I did not see this sooner. I am thinking we should leave the 'Sign in' dialog alone for now and update the dialog as part of porting the Join Flow to WWW.
