### ISSUE TITLE
Warn users when something in their project goes over the 10 MB asset size limit, the 2.5 MB JSON body payload size limit, or when the project goes over the 50 MB limit

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1188]
Ideally the warning would also include links or instructions for how to reduce the size of an asset/ project.

Currently, users encounter situations similar to https://github.com/LLK/scratch-flash/issues/1187 (which seems to be caused by project JSON exceeding the 2.5 MB limit) and don't have any indication of what is going wrong or what they can do to fix it.

From discussion with @cwillisf:

> I think the worst part [of the failure] is that it's enforced at upload time without even warning the user ahead of time
> like "You just added something big! You won't be able to save this project until you remove some stuff. Try this and that."

**Comment by jwzimmer** [comment]
(See comment thread in https://github.com/LLK/scratch-flash/issues/1187 for explanation of the size limits and related discussion.)

**Comment by TheLogFather** [comment]
Just a few notes carried over from #1187, much of which is fairly obvious, but may be worth having recorded here...

Since the json limit for online projects is now 2.5MB (down from 10MB) that means any existing project which breaks that limit can no longer be remixed. Also, any attempt to edit such a project (accidentally or otherwise) will result in failure to save. (Question: is it possible this could even lead to project corruption under some [rare?] circumstances? I have a vague recollection that might've happened to me a while back when I was building that 3d terrain project, but not totally sure...)

In the past, I've had occasions when editing a project that has too much variable/list data (so the json is too large) that it never stops showing the 'Saving...' text at top right. If this does happen I suspect many users may eventually just give up and click away to a different page, thereby losing all changes since last save (I know I did this a couple of times at first).

It seems a bit odd that there are (or were?) occasions when it doesn't (didn't?) show that 'network failure / failed to save' message/dialog, hence not giving a clear chance for the user to save to local disk.

However, I'll have a go over the next few days and see if I can still get it to do that – it's possible it's only under specific circumstances it happens like that (if it still does at all?)

**Comment by jwzimmer** [comment]
We should make sure we're clear with the units of the limits, see discussion around https://github.com/LLK/scratch-flash/issues/1187#issuecomment-241846921.

**Comment by jwzimmer** [comment]
This project 121280250 is giving me the network not connecting error when I try to remix it. I downloaded it and the unzipped size is 7,081,778 bytes (7.2 MB on disk) for 28 items. The largest asset is smaller than 10 MB but the project json is oversized (3.6 MB):
<img width="574" alt="screen shot 2016-09-23 at 10 57 59 am" src="https://cloud.githubusercontent.com/assets/1320456/18790410/ac2531bc-817c-11e6-8372-6edc2dc37a83.png">

The user had trouble uploading the project - they got server error: no response - but eventually they managed to upload it. They didn't see any warning about the data size limit. 

Since the oversize asset triggered server error: no response as well as the network not connecting error, it provides some support for the theory that that (project over size limit) is what happened in https://github.com/LLK/scratch-flash/issues/1202, etc.
