### ISSUE TITLE
Build Failure Because of Swfobject

### ISSUE THREAD

**Issue by algmwc5** [LLK/scratch-flash#1195]
http://swfobject.googlecode.com/files/swfobject_2_2.zip is a 404 link, since google stopped support for googlecode a while ago. This is causing build errors because the link above is a 404 link. The error is most likely caused by the downloads.xml file in apache flex's zip.

**Comment by DrKat123** [comment]
This [modified scratch.gradle file](https://github.com/SharpScratchMod/Sharp/blob/master/scratch.gradle) might help

**Comment by DrKat123** [comment]
bump

**Comment by DrKat123** [comment]
Bump

**Comment by DrKat123** [comment]
Bump

**Comment by thisandagain** [comment]
@cwillisf Any ideas?

**Comment by cwillisf** [comment]
@rschamp actually figured this one out last week. It turns out that the `swfobject` URL is hard-coded into the Flex (Flash) SDK, so the easiest fix is to bump the SDK version number to one that uses a non-Google Code URL for that download. That means going from Flex SDK 4.10.0 to at least 4.14.1, which makes me a bit nervous but should in theory be OK.

I'd suggest making that change and then doing some tests to make sure we didn't break compatibility with older versions of Flash; I could probably do that some time next week.

@DrKat123, if you would like to try this fix yourself, modify `scratch.gradle` like this:
```diff
diff --git a/scratch.gradle b/scratch.gradle
index aaa9a76..c821560 100644
--- a/scratch.gradle
+++ b/scratch.gradle
@@ -42,7 +42,7 @@ def scratchFlashCommitID = getCommitID(commonDir)
 println "Commit ID for scratch-flash is: ${scratchFlashCommitID}"
 dependencies {
-    flexSDK group: 'org.apache', name: 'apache-flex-sdk', version: '4.10.0', ext: 'zip'
+    flexSDK group: 'org.apache', name: 'apache-flex-sdk', version: '4.14.1', ext: 'zip'
     external group: 'macromedia.com', name: 'playerglobal', version: playerVersion.replace('.', '_'), ext: 'swc'
     merged files(
             "${commonDir}/libs/as3corelib.swc",
```
