### ISSUE TITLE
Send username of cloud variable change in cloud TCP stream.

### ISSUE THREAD

**Issue by PolyEdge** [LLK/scratch-flash#1206]
Right now, updates are transmitted in the format of
```
{
    "method":"set",
    "project_id":"<id>",
    "name":"<var>",
    "value":"<id>"
}
```

but there's no username. If there was a username in the data, all the scratch clients would be able to know who changed a variable last.

This would be a good idea for security, so user-written bots can monitor the cloud on their project for tampering, etc. without using the cloud log, which is broken right now.

This would allow scratch to generate its own logs of previous variable changes, and a sensor block that reports who changed a variable last.

It would look something like 
```
{
    "method":"set",
    "project_id":"<id>",
    "name":"<var>",
    "value":"<id>",
    "username": "<username>"
}
```

**Comment by TheLogFather** [comment]
Yes, I've often thought it'd be good to be able to ensure that a cloudvar change really is from the user it is claiming to be from (if the new value contains an encoding of the user's name).

Perhaps it'd even be nice to follow this up with a new block that gives the name of the last user to change the cloudvar...? (That'd avoid the need to encode it into the cloudvar, as long as the value and name isn't allowed to change within a refresh frame, so you can ensure the two definitely belong together.)

Could this info could be abused in some way?

**Comment by PolyEdge** [comment]
Well, a seeeecret project of mine requires verification of the username, or it could be abused, but right now I'm scanning a cloud log and #1205 is breaking it most of the time :cry:

**Comment by kaschm** [comment]
Thanks for the suggestion, but we're in the middle of redesigning cloud variables and won't be adding new features to the existing system in the meantime!

**Comment by TheLogFather** [comment]
Great to hear about the redesign of cloudvars. It'll be good to have the current NS holes filled in.

Your reply suggests the possibility that the server responses could end up being somewhat different to what they are now? Does it even mean that the API might be changing in some way?

If so, is there any chance of the new specs being made available to various users here before they are rolled out? It'll cause numerous problems for those of us who currently make use of it otherwise...
