### ISSUE TITLE
Unlimited cloud variables?

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-flash#1226]
I recently found a bug even if I press ok each time I still can get as many cloud variables that I want.

**Comment by algmwc5** [comment]
What _is_ the limit? because I'm experiencing the same issue

**Comment by CosmicWebServices** [comment]
I think it is 6-7?

**Comment by Airhogs777** [comment]
Iirc is supposed to be 10

Also, make sure that the cloud log says the variables were created correctly, it might just be making regular variables with the cloud icon

**Comment by CosmicWebServices** [comment]
good point. Let me check...

**Comment by MooShoe** [comment]
limit works fine for me.

**Comment by jwzimmer** [comment]
Hi @CosmicWebServices, @Airhogs777 - Why are you thinking there is a limit on cloud vars? 
Are you seeing browser/flash console errors with a status of 429 when you hit the limit? Thanks.

**Comment by CosmicWebServices** [comment]
I am not but there was always a popup or it did not let me select the cloud var option if I reached about 6 cloud vars

**Comment by jwzimmer** [comment]
Ah, I see - 
<img width="315" alt="screen shot 2016-10-31 at 5 16 45 pm" src="https://cloud.githubusercontent.com/assets/1320456/19872044/33387036-9f8e-11e6-96c1-6ab49d79a2f1.png">

Thank you!

**Comment by Airhogs777** [comment]
@jwzimmer the limit of 10 cloud vars is listed on the wiki: https://wiki.scratch.mit.edu/wiki/Cloud_Data#Current_Status

Is that limit no longer being enforced? If so, I'll update the page to reflect that.

**Comment by TheLogFather** [comment]
The project editor (still) 'enforces' the limit of ten cloudvars by dimming the cloudvar check box once it detects that you have created ten cloudvars.

Since the limit is imposed client-side, there are numerous ways around it, of course.

And that also means there are several ways that it can go wrong. (As a simple example, if cloud is a bit slow, and you make a cloudvar with the same name twice in quick succession, so the cloud server didn't responded quickly enough the first time, then it lets you do the same name again – and the project editor counts *both* times as having created a cloudvar, even though the server didn't bother to do anything the second time.)

**Comment by jwzimmer** [comment]
Thank you @Airhogs777, @CosmicWebServices & @TheLogFather. I'll look into what the state of the limit should be... Thanks for your help. : )

**Comment by CosmicWebServices** [comment]
No problemo

**Comment by cwillisf** [comment]
The current "limit" is 10, but like @TheLogFather said the enforcement is somewhat weak. Users on a slower or busy Internet connection will likely have an easier time bypassing the limit.

We're talking about overhauling our cloud variable architecture in general, so between that and Scratch 3.0 I think we'll fix this along the way. Fixing this in the current architecture isn't a priority, though.

Note to future selves: to find the code currently enforcing the limit, look for `persistentDataCount` toward the bottom of `VariableSettingsOnline.as` in the online editor codebase.

**Comment by jwzimmer** [comment]
Thanks @CosmicWebServices, @Airhogs777 & @TheLogFather for helping me look into this. So, the limit of 10 cloud vars per project does stand. It takes a lot of resources to support each cloud var, both locally and on our end, so when you create projects with cloud vars, you could be hitting either limit. We know our current implementation of cloud vars could certainly be improved and plan to address that in the future. However, even then, we won't be supporting unlimited cloud variables, in part because we want Scratch projects to be playable by most users, even those with fewer network resources available. Thank you for your suggestion!
