### ISSUE TITLE
Asset Loading fails silently

### ISSUE THREAD

**Issue by DavidBuchanan314** [LLK/scratch-flash#1233]
See this, for example: https://scratch.mit.edu/discuss/topic/226097/

When an asset does not load properly due to adverse network conditions etc., something should happen. Either the whole project should be prevented from loading, or the download should be reattempted. Perhaps the MD5 hash of assets should also be validated.

The current behaviour allows trivial cheating by selectively blocking sprite images.

**Comment by cwillisf** [comment]
Thanks for your concern, @DavidBuchanan314! Unfortunately, I think a comprehensive approach to preventing this kind of cheating would conflict with some of our tinkering-friendly goals. We could do better than the current editor's behavior, though, and we're planning on improving this for Scratch 3.0.

The basic problem is that there's no good option for recovery if we find that a particular asset fails to load or loads incorrectly:
- We could (and probably should) try again, depending on what sort of error was encountered. If it's a 404 or mismatched MD5, though, trying again isn't likely to help.
- We could replace the asset with some default. This will likely change the behavior of a project, but might be better than "hiding" the failure. This won't prevent intentional cheating, though.
- We could declare that the project as a whole failed to load. This could prevent cheating, but could also prevent recovery from genuine errors. If a single asset becomes corrupted or goes missing I would still want people to be able to load and remix the project; depending on which asset is affected the project's educational and inspirational value is likely still intact.

I plan to implement retries and default fallback assets (the first two bullet points) in Scratch 3.0, but I think blocking or redirecting a particular asset is something that we probably won't explicitly protect against. If you'd like your game to be prevent this sort of cheating then I would recommend checking your sprites' costumes as part of the game's code, using `touching {sprite}` or `touching color {}` blocks during an initialization phase or something like that. Keep in mind that there are plenty of other ways to cheat in a Scratch-based game, though, or even browser-based games in general.

For now I'll close this in favor of Scratch 3.0 work already in progress, but I'm open to discussing this further if you're interested.
