### ISSUE TITLE
Stage3D causes incorrect scaling on sprites

### ISSUE THREAD

**Issue by DanFessler** [LLK/scratch-flash#1242]
My browser / operating system: Windows NT 10.0, Firefox 50.0, Flash 23.0 (release 0)

Originally reported this in 2014, but had no response. The bug is still there. This becomes a pretty critical bug when dealing with perfect sprite alignments such as tile engines.

Bug demonstration:
https://scratch.mit.edu/projects/22695940/

**Comment by TheLogFather** [comment]
Stage3D can do all kinds of weird things to the scaling of sprites.
At the moment, I have a feeling there's something not quite right, and somewhat random, about the way it caches certain pixel information when scaling a costume (causing a vector sprite to become blurry in some cases when upscaling the existing pixels, rather than redrawing the vector costume at higher resolution).

But the effect you're describing is more subtle, and I'd guess is related to various subtle differences in the way that scaling is done using the Stage3D API (compared to the standard path). Consequently, I'm not sure there's much can be done about such differences...  :(

Of course, you can probably ensure the scaling of your tiles is correct for either Stage3D enabled (i.e. when a relevant effect block is in project) or Stage3D off (no such block).
But, given there seem to be a significant fraction of users with a computer/browser/OS/Flash that does not correctly recognise the ability to use Stage3D (and so won't switch into it when a relevant effect block is present), the only way to be consistent across machines is to not use Stage3D.  :/

**Comment by DanFessler** [comment]
Yeah I've noticed the blurry vector issue as well, perhaps someone should open an issue for that as well.

But with the scaling bug, one possibility that crossed my mind is it might simply be just a bug in the fragment shader that makes it just slightly off.  That'd certainly make for an easy fix if it is.
