### ISSUE TITLE
Incorrect mask value in getBitmapWithoutSpriteFilteredByColor()

### ISSUE THREAD

**Issue by DavidBuchanan314** [LLK/scratch-flash#1258]
This function is used as part of the various colour sensing blocks. It would appear that this sensing is deliberately "fuzzy", and as such only the most significant bits are checked, using the mask 0x00F8F8F0:

https://github.com/LLK/scratch-flash/blob/abac440f1f34932679bd001d96de2315be7020ee/src/scratch/ScratchStage.as#L643

A later comment says "match only top five bits of each component":

https://github.com/LLK/scratch-flash/blob/abac440f1f34932679bd001d96de2315be7020ee/src/scratch/ScratchStage.as#L655

If this is the intended behaviour, shouldn't the mask be 0x00F8F8F8 ?

**Comment by liam4** [comment]
I *think* there was a discussion about this, a long time ago, about how green was more visible than other colours to the human eye, which helped them make the mask this way. But I couldn't tell you where that happened.

**Comment by TheLogFather** [comment]
This was already 'fixed'...
https://github.com/LLK/scratch-flash/commit/d592ffa00c5378d2da2a90a6ce0dca0a5f57fa4f

...then reverted:
https://github.com/LLK/scratch-flash/issues/544
https://github.com/LLK/scratch-flash/commit/41eca4a22d14bde0c90df2ff9723163af3b9c02e

As you see above, changing it potentially breaks some projects (though it wouldn't be the first time a change has broken projects...) In particular, it'll break a number of projects which are aware of the mask value, and make use of it when checking for colour-matching. (Also, it already takes over a second for a project to check through all 32x32x16 colours, to find the colour at a pixel. Doubling that... well... not the best argument, but, y'know...)

Also, I think it works well enough as is for human visual perception, since the blue component is darker than red & green components, so changing the blue component by one makes less apparent difference than changing red & green components.

**Comment by DavidBuchanan314** [comment]
Ah. Perhaps the comment could be expanded to explain this? Something like:

"Mask value chosen to correspond with human colour perception, and to maintain compatibility with existing projects"
