### ISSUE TITLE
Selecting Dari language just shows English

### ISSUE THREAD

**Issue by asweigart** [LLK/scratch-flash#1263]
Selecting "Dari" (an Afghani language) from the language menu in v453 offline editor and on the website both just show English code blocks and menu items.

**Comment by chrisgarrity** [comment]
We have a mismatch between what's in the code and what languages are being translated. I'm not sure how Dari (language code fa_AF) was added to the language menus, but it is not available on the translation server. Since there are no translations on the server it shows the default English strings for everything. 

We should remove Dari from the menu, and reinstate it when it has actually been translated. I'm also not sure that `fa_AF` is the correct language code - Ethnologue uses `prs`.

**Comment by asweigart** [comment]
I've also notice Latina is missing the the translation for "turn clockwise" and "turn counterclockwise" blocks. We may want to write a unit test to check for untranslated languages or blocks.

**Comment by chrisgarrity** [comment]
@asweigart Languages do not have to reach 100% to be included, so having missing strings is acceptable.

**Comment by chrisgarrity** [comment]
@asweigart Thanks for bringing this to our attention. I've opened issues on the code repositories to remove Dari from the menus for now. I'm closing the issue here.
