### ISSUE TITLE
Dragging sprite, the clone get bigger.

### ISSUE THREAD

**Issue by togazo** [LLK/scratch-flash#1269]
When I drag the cat, cat's clone get bigger.
This matter occered fullscreen-mode only.
Is this bug? I want to show this sprite with the same size.

- Project: https://scratch.mit.edu/projects/141757353/
- windows10/Chrome(ver.55/64bit)/
- (another: MacOsX ElCapitan/Chrome(ver.55/64bit)/FireFox(50.1.0))
- sprite: "can drag in player :" checked

![2017-01-26](https://cloud.githubusercontent.com/assets/6989972/22297069/8abf6264-e35f-11e6-8ced-a9839cf4c43c.png)
![2017-01-26 1](https://cloud.githubusercontent.com/assets/6989972/22297068/8abb4f44-e35f-11e6-9513-c0a4aa9c59ca.png)

**Comment by CosmicWebServices** [comment]
For some reason it is not working for me

**Comment by togazo** [comment]
Did you change fullscreen-mode and click the green flag?

**Comment by CosmicWebServices** [comment]
now I did btw I am IcyCoder

**Comment by togazo** [comment]
Oh, sorry. I see.

**Comment by liam4** [comment]
Yeah, I can reproduce this. Issue only happens in fullscreen, Stage3D doesn't seem to matter.

This project demonstrates that the Scratch sprite is actually getting [scaled up](https://scratch.mit.edu/projects/141797776/), so it's not a rendering issue.

I'd imagine the issue would be the same as what happens when you try to scale a 0-pixel sprite? My guess was that the sprite's costume isn't loaded when it's cloned. But I did a little bit of experimenting and didn't find much.. https://scratch.mit.edu/projects/141798287/

**Comment by TheLogFather** [comment]
Should note this is probably the same as in https://scratch.mit.edu/projects/75594376/
Sprite size not dealt with correctly during drag when size of project screen isn't actually 480x360 pixels – in other words, when in fullscreen *or* when the browser zoom is not 100%.
(Note that Chrome is likely an exception in that last case, since it does its zoom in a different way...)

**Comment by TheLogFather** [comment]
(Just wondering: does this still "needs repro"...? –The project link I gave above should show at least what I suspect is likely the same issue with a miscalculation of on-screen size during built-in drag.)
