### ISSUE TITLE
Scratch is converting "1.0" to "1" in numeric placeholders - breaks pick random block

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#1270]
* Create a project with one script that reads (pick random -1.0) to 1.0).
* Save the project.
* Close and reload the project

Result is that the pick random has now been changed to -1 to 1.

This is bad because it results in a totally different results.

This did not used to be the case because I have projects where I use 1.0 for this very reason. This is also impacting Scratch 3 as it loads them without the decimal place too. This could be down to storing the arguments as numbers in the exported/saved JSON as this may trim the redundant decimal places?

**Comment by CosmicWebServices** [comment]
I noticed this problem and I think I used a join block to fix it...

**Comment by TheLogFather** [comment]
Was wondering when this would finally make its way into here... :)

@griffpatch: This happened a while back when the strange addition of an "epsilon" was removed from integer values: https://github.com/LLK/scratch-flash/pull/698

It's possible to work around it by 'hacking' a string value of "1.0" into the slot in the JSON (rather than a numeric value). –That doesn't get changed back to numeric 1, but remains as string "1.0".

**Comment by cwillisf** [comment]
Here's my attempt at documenting the current behavior in Scratch 2.0 and what I believe to be the desired behavior. Please let me know if you think I've missed anything or have anything wrong, including if you think the desired behavior is different from what I've laid out below.

Assume that we're running a `random {} to {10}` block, and the value from the table's leftmost column is inserted as the first argument. I've used "int" and "float" here as shorthand for whether the editor will return only integer values or include fractional values.

| First argument | Current behavior | Desired behavior | Notes |
| - | - | - | - |
| 1 | int 1..10 | int 1..10 | |
| 1. | float 1..10 | float 1..10 | a |
| 1.0 | float 1..10 | float 1..10 | a |
| 1e-1 | float 1..10 | float 1..10 | b |
| 10e-1 | int 1..10 | float 1..10 | b |
| 10.e-1 | float 1..10 | float 1..10 | a, b |
| 1ee | int 0..10 | float 0..10 | b, c |
| 1.. | float 0..10 | float 0..10 | a, c |
| Reporter with value "1" | int 1..10 | int 1..10 | |
| Reporter with value "1.0" | int 1..10 | float 1..10 | d |
| Reporter with value "0.1" | float 0.1..10 | float 0.1..10 | |

(a) - Any string containing '.' is treated as non-integer.
(b) - IMO scientific notation should force float result for consistency.
(c) - Any parse error causes the value to be treated as zero.
(d) - A reporter is treated as an integer if and only if its numeric value is integral. That is, note (a) does not apply to reporters.

**Comment by TheLogFather** [comment]
@cwillisf:
Whilst there are certainly some questions concerning desired(/expected?) behaviour with reporters and scientific notation in the arguments, the problem being discussed here is that those arguments can *change* after being saved and reloaded, and thereby change (likely, break) the behaviour of the project (simply by reloading it).

Try the following:
1) Create a new, blank project.
2) Place a "pick random" block, and enter arguments "0.0" to "1.0".
As expected, it gives float values from 0 to 1.
3) Now save the project (to disk, or online), and leave the page.
4) Now reload the project.
Note that the arguments are now "0" and "1", rather than "0.0" and "1.0".
This will clearly now give only values zero or one (rather than a float between 0 and 1).

**Comment by TheLogFather** [comment]
The arguments of "pick random" are effectively a very special case – they have attributes of being a *string* argument, rather than numerical (i.e. their behaviour depends upon certain characters in the actual string), but the slot should still *look* like a numerical argument (i.e. round ends, rather than square ends), and act like it's a numerical argument (i.e. only allowing digits, dot, minus, and letter "e").

Therefore, perhaps the the simplest 'fix' in the coding would be to actually do that:  treat them as string arguments internally, but draw the slots as numerical, and only allow numerical entry.

Would this be best done by creating a brand new argument type? Or is that overkill for just the one block?

**Comment by cwillisf** [comment]
@TheLogFather thanks for all the detailed thought about this! Part of the reason I'm looking into this issue is to make sure that we get the behavior right for Scratch 3.0; that's why I wanted to look at the behavior of the "pick random" block at runtime as well as at save/load time.

I'm definitely focusing on the save/load problem but I want to make sure that I don't break any other desired aspects of the current behavior. If I can fix a few cases along the way then that's even better :)

**Comment by TheLogFather** [comment]
OK, great...

Yeah, "pick random" has certainly proved, in various ways, to be a bit more of a pain than you'd expect.
I guess that's why I've been thinking that creating a new special argument type may be a prudent option – to ensure it separates all its oddities out from everything else.

**Comment by cwillisf** [comment]
Well... the fix I settled on wasn't in the part of the code that I expected it to be in, so there shouldn't be any effect on the table above.
