### ISSUE TITLE
Create "save to local file" option for backdrops to match sprite "save to local file" option

### ISSUE THREAD

**Issue by asweigart** [LLK/scratch-flash#1272]
The user is able to right-click on sprites in the Sprite Area and select "save to local file" to download the sprite as an image file. This option is not available for the backdrops. (Though you can click the Backdrops tab and then right-click on the backdrops there. This is also true for sprites on the Costumes tab.)

This would bring parity between backdrops and sprites.

**Comment by TheLogFather** [comment]
Hmmm, there are some 'issues' here...

The "save to local file" in the sprite's right/shift-click menu refers to saving the whole sprite, not the current costume. So what would "save to local file" do in the backdrop's menu? (Would it save only the backdrop 'costume', or would it save the whole Stage, i.e. scripts and all, which would really be 'parity' with the sprite's one – and something we are kinda missing at the moment...)

There is already "save picture of stage", but that's rather different of course.

I think it's initially a bit unclear what "save to local file" in the sprite's menu will actually do – I mean, when you first see it, will it save the sprite, or will it save the costume? All other items in the menu refer to the sprite itself, so it makes a bit more sense that it would be the actual sprite, rather than costume, but it's not 100% obvious.

Maybe the sprite's menu item should be changed to "save *sprite* to local file", and then the new item in the backdrop's menu would be "save backdrop to local file"...? (So it's not really 'parity' then.)

**Comment by asweigart** [comment]
That's true. I'd argue it's not important enough to come up with a ".sprite2" file except for backdrops. Perhaps a menu name change would be a good way to clarify this: "save sprite to local file" and "save costume to local file" for the sprites.
