### ISSUE TITLE
404 link for cloud variable notification

### ISSUE THREAD

**Issue by asweigart** [LLK/scratch-flash#1281]
When the user creates a cloud variable, a notification appears at the top of the editor pointing them to the Cloud FAQ. Currently, this links to https://scratch.mit.edu/help/faq/#clouddata which doesn't exist.

I believe the correct link is https://scratch.mit.edu/info/faq#clouddata

**Comment by jwzimmer** [comment]
I thought there might be a duplicate issue for this, and potentially a PR fixing it, but I cannot find it, and the link 404s on Staging as well. So I think this does still need to be fixed.

**Comment by thisandagain** [comment]
@cwillisf @jwzimmer This isn't `prio-critical` but I'm wondering if we might want to consider patching this considering it's a) minimal / low-risk b) high impact for the moderation team

**Comment by Paddle2See** [comment]
@thisandagain

This issue is still happening, as mentioned in this recent forum topic https://scratch.mit.edu/discuss/topic/284094 

Since this is our first line of defense against cloud-based chat projects, which we recently decided to dis-allow in most cases (per recent Community meeting), we should perhaps fix this in time for our announcement of the new policy.

**Comment by thisandagain** [comment]
@Paddle2See Moving into the December milestone.

**Comment by Kenny2github** [comment]
@cwillisf did you close this because the issue is resolved...?

**Comment by colbygk** [comment]
@Kenny2github It will be resolved today.
