### ISSUE TITLE
languages with locale not getting updates.

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-flash#1301]
I think this only applies to the languages that have a locale in addition to language code, such as zh-tw, zh-cn and pt-br.

In transifex the langauge code for Chinese (Taiwan) is zh_TW. However, django wants the po file code in the form zh-tw. scratchr2_translations has [configured](https://github.com/LLK/scratchr2_translations/blob/master/legacy/.tx/config) transifex to map zh-tw to zh_TW and vice versa.

The editor/static/locale folder in [scratchr2_translations](https://github.com/LLK/scratchr2_translations/tree/master/legacy/editor/static/locale) only has the zh-tw.po file.

I'm not sure where the flash online editor is getting its po files, so the problem is easier to see in the offline editor.

In transifex the current zh_TW translation for 'repeat %n' is '重複 %n 次'

In the scratch flash offline locale directory there are both zh_TW.po and zh-tw.po files.

The translation for repeat %n in zh_TW.po is the correct one: 重複 %n 次. 
The translation in zh-tw.po is out of date: 循環 %n 次. 

But it is the out of date one that is getting built into the editor:
![screen shot 2017-05-03 at 12 06 44 pm](https://cloud.githubusercontent.com/assets/399209/25669906/0c9287ae-2ff9-11e7-9e57-6c926f5e3466.png)

**Comment by cwillisf** [comment]
The online editor gets its PO files from [`scratchr2/static/locale/`](https://github.com/LLK/scratchr2/tree/develop/static/locale) -- specifically, it will load `scratchr2/static/locale/${LANG}.po` where `${LANG}` is one of the items from the first column of `scratchr2/static/locale/lang_list.txt`. The offline editor does the same thing, but from [a local copy of `scratchr2/static/locale/*`](https://github.com/LLK/scratch-flash-offline/tree/develop/src/locale).

It seems like we have two options for fixing this:
- Standardize on "zh-tw": delete `scratchr2/static/locale/zh_TW.po` and adjust the script(?) which generates those files so that it updates `zh-tw.po` instead.
- Standardize on "zh_TW": delete `scratchr2/static/locale/zh-tw.po` and adjust `lang_list.txt` to specify "zh_TW" instead.

It looks like the language cookie for the website uses "zh-tw" so it's probably better to use that. In particular, that should make it so that setting your language on the web site carries over correctly to the editor.

**Comment by chrisgarrity** [comment]
In that case I think it's all languages that are not getting updated. When we moved to transifex, we combined the blocks and editor-ui po files into one file, and that is in scratchr2_translations [editor/static/locale](https://github.com/LLK/scratchr2_translations/tree/master/legacy/editor/static/locale). @mewtaylor Is there a script that should be syncing the submodule with scratchr2/static/locale?

@cwillisf I think we should be standardizing on zh-tw as that one seems to be what most of our code wants, and remove zh_TW and any other obsolete po files that are left.

**Comment by chrisgarrity** [comment]
@cwillisf I checked in with Matt, scratchr2/static/locale is getting updated from the scratchr2_translations submodule (there's a script that copies them). So it's just the languages with locales, and I think we should standardize on 'zh-tw'. Does that make sense to you too?

**Comment by cwillisf** [comment]
Yep - that makes sense. Two questions, though:
- Where is the script that copies files from `scratchr2_translations`?
- When does that script run? Is it manual?

**Comment by chrisgarrity** [comment]
static/locale/* po files are getting updated in the _Pull translations from Transifex_ Jenkins job. On closer inspection, they're not copied from scratchr2_translations, they're pulled directly from transifex. It happens at the same time as the scratchr2_translations get updated so they should be identical.

One immediate issue is that the scratchr2 .tx/config is missing the configuration that maps zh_TW.po to zh-tw.po. I'll update scratchr2 to fix the config and remove any obsolete po files (i.e. ensure that if you pull updates from transifex, then the editor/static/locale files in both locations are identical). Then can you check the building the editor?

**Comment by cwillisf** [comment]
👍 sounds good!

**Comment by chrisgarrity** [comment]
scratchr2_translations repo no longer has duplicate po files for languages with locale. Transifex standard language code is mapped the one expected by scratchr2. (e.g., zh_TW.po is mapped to zh-tw.po) The current zh-tw.po file has the correct 'repeat %n' translation: "重複 %n 次".

Scratchr2 has also been updated, and the static/locale/zh-tw.po also has the correct translation: "重複 %n 次"so things look good, but we'll need to rebuild the offline editor if it hasn't been done already.

**Comment by cwillisf** [comment]
Thanks for the update! I'll make sure this gets into this iteration's build of the offline editor.

**Comment by chrisgarrity** [comment]
Tracking  QA in https://github.com/LLK/scratchr2/pull/4635
