### ISSUE TITLE
Cannot display Japanese Hiragana translations at にほんご  (ja_HIRA.po) locale.

### ISSUE THREAD

**Issue by abee2** [LLK/scratch-flash#1317]
Check the following screenshot. I found this problem on 464.
My browser / operating system: Windows NT 10.0, Chrome 58.0.3029.110, Flash 25.0 (release 0)
![2017-06-03 17 53 06](https://cloud.githubusercontent.com/assets/972987/26752266/d96ed1f6-4886-11e7-9b9e-5038e0448d4b.png)

**Comment by abee2** [comment]
It seems that ja-Hira.po is used for translation instead of ja_HIRA.po. ja_HIRA.po is correct translation file.  ja-Hira.po is almost empty. I'm not sure why this file exists.

**Comment by chrisgarrity** [comment]
@abee2 Yes, it appears that things didn't go well for ja-Hira. The language code on Pootle and the language code on Transifex don't match so it didn't pull over the translations. I manually uploaded the last blocks/editor po files from pootle to ja-Hira in Transifex, but you should probably review them. Next time the editor is built it should include all the reviewed strings. From now on all updates should be in ja-Hira on Transifex, and there should not be a ja_HIRA file at all. 

@cwillisf Can you check what file the editor is actually using when it's built? scratchr2 actually expects Japanese (Hiragana) to be in the file ja-hr.po, so that's what is in [scratchr2_translations](https://github.com/LLK/scratchr2_translations/tree/master/legacy/editor/static/locale).

**Comment by abee2** [comment]
@chrisgarrity @cwillisf  Thank you. I understood the situation. And I've reviewed all words of ja-Hira. I hope early release of next version. Many Japanese schools are affected by this problem. Thanks for your help.

**Comment by rschamp** [comment]
This should be resolved with the next translation deploy and offline build.
