### ISSUE TITLE
Logarithm issue

### ISSUE THREAD

**Issue by PiotrGrochowski** [LLK/scratch-flash#1318]
I found a bug, called "Logarithm issue".
abs(log(7/5)-log(sqrt(2)))
abs(log(10/7)-log(sqrt(2)))
The lower one gives a slightly smaller value. This is important, as my project thinks 10/7 is a better approximation than 7/5 with logarithmic error calculation. This is a floating point rounding issue. If you want to suggest a workaround, please use a compromise one that deals with high accuracy while also providing correct equality. Please fix "Logarithm issue".

**Comment by TheLogFather** [comment]
No, you're thinking about it in the wrong way – the second one *is* smaller (rounding error is not relevant).

The log curve has a high curvature near one, so the comparison is skewed in a way that does not match with your own idea of 'closest'.

If you want to compare two values, A and B, in a way that matches more closely with your intuition then you'd be better using:  "abs(A/B-1)"

**Comment by PiotrGrochowski** [comment]
It's not "my intuition". My project calculates approximations of numbers with fractions and requires error calculation to check if the new fraction is more accurate than the less complex one. I recently implemented logarithmic error calculation as an option, but I ran into "Logarithm issue" while calculating fraction approximations for sqrt(2). Note that logarithmic error is important, for example in calculating musical pitches.
abs(7/5/sqrt(2)-1)=0.01005050634
abs(10/7/sqrt(2)-1)=0.01015254455
It would detect 10/7 as less accurate, while they are actually equal logarithmically.

**Comment by TheLogFather** [comment]
OK, yes, I understand you what you mean. (And yes, I understand the importance of logarithmic comparison for frequencies in musical intervals.)

But still, it's not something that can be fixed.

As I said above... it is a *fact of life* when using floating-point numbers on computers.
*You* have to take it into account whenever you code things that involve numerical computations with floating-point numbers.

It's really important to understand this aspect of computation (indeed the title of the paper I linked you to above is "What Every Computer Scientist Should Know..."), and that you will eventually and continually hit up against it whenever you use floating-point arithmetic, and you must therefore write code that takes it into account – no matter which programming environment you're using (i.e. this not specific to Scratch).

**Comment by PiotrGrochowski** [comment]
That means that it's impossible to produce a correct list of fractions with lower logarithmic error than the simpler ones, right?

**Comment by TheLogFather** [comment]
If floating-point really were *that* horrible then nobody would use it, but would find a better alternative.

Since the vast majority of numerical computations run on computers make use of floating-point arithmetic, that should tell you something important!  :)

There really isn't an alternative if you're dealing with real numbers. You can perform operations with higher and higher precision floats, but there will always come a point where they don't do what you might naively expect them to do.

A good example is the number 0.1, a value that is very common to see used in computational code (and, for example, in a Scratch project where someone wants to work out a score in tenths of a unit). But that number *does not exist* in *any* binary floating-point format – simply because it has an infinite number of binary digits, and so cannot be stored by any finite storage.

If you then do arithmetic with the number that's not-quite-0.1, then it's quite possible you will get an answer that isn't what you expect (e.g. multiply it by 10, and you *don't* get exactly one).

You could ask then why we don't make computers that work in decimal instead. The answer is that (1) that's less efficient for computation and (2) it still has exactly the same problem for many numbers (e.g. think about dividing one by three...)


If you want to get it to say the two values are the same (logarithmic) distance from sqrt(2), then you really have two choices...

(1) You must allow for potential errors, and just say they are 'near enough the same'. (I.e. if they are the same to with 10^-10 or so.)
This will likely be fine if you're only dealing with integers in your fractions up to several thousand.

(2) You must find rewrite your equations in such a way that the comparison ends up only using integers and multiplications. (I can explain more if you want, but in the specific example you give above, the end result is that it compares 2401*2500 against 2450*2450, and finds they are the same.)
Since normal integers in Scratch are also limited as floats, this will limit the possible ints in the top/bottom of the fraction to only a few hundred. However, you could do much better by looking instead at the prime factors of the various integers involved, and factorising out where you can. (The ultimate would be to use arbitrary-precision integer arithmetic, by writing your multiplication algorithms that allow any length of integer... –There are some arbitrary-precision arithmetic Scratch projects out there, so you could take a look for those, if you want to pursue that path,)

Hope that kinda makes *some* sense, somewhere!

**Comment by PiotrGrochowski** [comment]
Rounding to nearest 10^-14 gave me correct results!

**Comment by PiotrGrochowski** [comment]
By the way, if you would like my library of scratch projects (since my Scratch account is banned) use this Dropbox link: https://www.dropbox.com/s/2qgxpsedsstn1wk/scratch%20projects.rar?dl=0
