### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-flash#1323]
There are strings in the editor that don't appear in the editor.po file:
- 'info' - in Sprite context menu;
- 'rename broadcast' - in 'broadcast' block context menu;
- 'crop to selection' - tooltip for crop button in costume editor (bitmap mode);
- 'erase all' - tooltip for clear button in costume editor;
- 'add comment here...' - default text when you add a new comment.

**Comment by sfederici** [comment]
Further strings not translated in the editor:
- 'backdrop1' - in 'switch to backdrop' block and 'when backdrop switches to' block
- 'meow' - in 'play sound' block
- 'cannot add: that name is already in use' - when creating a variable with an already existing name
- 'what's your name' - in 'ask' block
- 'hello' and 'world' - in 'union', 'letter' and 'length of' blocks

**Comment by chrisgarrity** [comment]
More missing strings (related to recording video):
* 'Capture and download a video of your project to your computer.\nYou can record up to 60 seconds of video.'
* 'You can also share your video with others to let them see it!'
* 'To play your video, download and install the'
* 'VLC media player.' (separate because this part is a link)

**Comment by gunchleoc** [comment]
Note that when "'Record & Export Video'" gets fixed, we will probably also have to fix the corresponding FAQ entry, which still says "Record Project Video". https://www.transifex.com/llk/scratch-website/translate/#gd/faq-l10njson/102348190

**Comment by sfederici** [comment]
Further strings not translated in the editor:
- "Extension problem: See the 'Tips' window (on the right) to install the plug-in and get the extension working' when adding an extension (e.g. the PicoBoard extension)
- 'motor', 'motor A', 'motor B', 'lights', 'everything' in menus of Lego WeDo 1.0 extension
- 'all motors' in menus of Lego WeDo 2.0 extension
- 'set direction to' block in Lego WeDo 2.0 extension
- 'set light color to' block in Lego WeDo 2.0 extension
- 'play note for seconds' block in Lego WeDo 2.0 extension
- 'when tilted' block in Lego WeDo 2.0 extension
- 'tilted?' block in Lego WeDo 2.0 extension
- 'tilt angle' block in Lego WeDo 2.0 extension

**Comment by sfederici** [comment]
Further strings not translated in the editor:

- 'Save Project Summary' in shift-clicked File menu
- 'Show version details' in shift-clicked File menu
- 'Esport translation strings: commands' in shift-clicked Edit menu
- 'Esport translation strings: UI' in shift-clicked Edit menu
- 'Esport help screen names' in shift-clicked Edit menu
- 'Edit block colors' in shift-clicked Edit menu
- 'Medialib: media' in shift-clicked Edit menu
- 'Medialib: sprites' in shift-clicked Edit menu
- 'Medialib: check JSON file' in shift-clicked Edit menu
- 'Edit block colors' in Edit Block Colors window
- 'Load' in Edit Block Colors window
- 'Category: Motion' in Edit Block Colors window
- 'Apply' in Edit Block Colors window
- 'Hue' in Edit Block Colors window
- 'Sat.' in Edit Block Colors window
- 'Bri.' in Edit Block Colors window

**Comment by radioblahaj** [comment]
Whats help-wanted here?

**Comment by sfederici** [comment]
Several strings are missing in the *.po files, so that they cannot be translated in the Scratch GUI, e.g. 'rename broadcast', 'add comment here...'. Adding those strings in the po files make them show up correctly translated in the GUI. 

Several other strings instead are not inclosed in the internationalization function In the GUI code, e.g. 'What's you name?', 'That name is already in use'. Adding these strings to the po files is not enough.

What to do:
- add missing strings in the po files
- add call to internationalization function in the GUI code for all strings that must be translated in the po files

A revised list of missing translations follows (newly added strings are highlighted by '+'):

'info' - in Sprite context menu;
'rename broadcast' - in 'broadcast' block context menu;
'crop to selection' - tooltip for crop button in costume editor (bitmap mode);
'erase all' - tooltip for clear button in costume editor;
'add comment here...' - default text when you add a new comment.
'cannot add' + 'that name is already in use' - when creating a variable or list with an already existing name
'what's your name' - in 'ask' block
'hello' and 'world' - in 'union', 'letter' and 'length of' blocks

MISSING STRINGS RELATED TO VIDEO RECORDING:
In 'Record Project Video' dialog when choosing File > Record Project Video):
'Capture and download a video of your project to your computer.\nYou can record up to 60 seconds of video.' 
+'Include sound from project'
+'More options'
+'include sound from microphone'
+'Show mouse pointer'
+'Record entire editor (may run slowly)'
+'Record at highest quality (may run slowly)'
+'Fewer Options'
+'Please note that the video will not be saved on Scratch'
+'Start'
During recording (on Stage):
+'To stop recording click the square'
+'Writing video to file...'
When finished recording (in 'Video finished' dialog):
+'Video finished'
+'To save click the button below'
+'Save and Download'
When asked to save video (in 'Playing and Sharing Your Video' dialog):
+'Playing and Sharing Your Video'
'To play your video, download and install the'
'VLC media player.' (separate because this part is a link)
'You can also share your video with others to let them see it!'
+'Questions?'
+'Back to Scratch'

MISSING STRINGS RELATED TO EXTENSIONS:
'Extension problem: See the 'Tips' window (on the right) to install the plug-in and get the extension working' when adding an extension (e.g. the PicoBoard extension)
In extension menu:
+'Info ... extension'
+'Remove extension blocks'
'motor', 'motor A', 'motor B', 'lights', 'everything' in menus of Lego WeDo 1.0 extension
'all motors' in menus of Lego WeDo 2.0 extension
'set direction to' block in Lego WeDo 2.0 extension
'set light color to' block in Lego WeDo 2.0 extension
'play note for seconds' block in Lego WeDo 2.0 extension
'when tilted' block in Lego WeDo 2.0 extension
'tilted?' block in Lego WeDo 2.0 extension
'tilt angle' block in Lego WeDo 2.0 extension

**Comment by Kenny2github** [comment]
Where is the editor.po file?

**Comment by sfederici** [comment]
The *.po files are in the "locale" folder. I don't know of an editor.po file.

**Comment by Kenny2github** [comment]
There doesn't seem to be a `locale` folder available in the repo...?

**Comment by sfederici** [comment]
I guess you can take it from any installed Scratch 2.

**Comment by Kenny2github** [comment]
Ah, true. There isn't an "editor.po" file though...

**Comment by sfederici** [comment]
Yes. Maybe Chris was referring to the "po files that translate the strings shown in the editor"? All strings, as far as I know, are in po files (there is one specific for each language) in the "locale" folder you can find in every offline Scratch2 installation (as it was in Scratch 1.4 too).
