### ISSUE TITLE
No-refresh to broadcast to no-refresh is painfully slow

### ISSUE THREAD

**Issue by PiotrGrochowski** [LLK/scratch-flash#1339]
When I do this:

when gf clicked
test (no refresh)

define test
broadcast [v test]

when I receive [v test]
test2 (no refresh)

define test2
complex script

It's painfully slow.

**Comment by TheLogFather** [comment]
What you have given above doesn't look to me as though it will do anything different from the following:

when gf clicked
test2 (no refresh)

define test2
complex script

If your complex script is taking more than a few seconds to run then it'll cause the Scratch interface to become laggy, because Scratch only checks the UI every half second during non-refresh.

In particular, if the complex script is doing lots of drawing, then it can even cause Scratch to become unresponsive (because committing the pen strokes to screen ends up taking way longer than just the half- second non-refresh limit).

Is there something else you're doing that you haven't shown.
Can you share an actual example project?

**Comment by Kenny2github** [comment]
@TheLogFather this is an issue I've found before, it's specifically "broadcast [ v] and wait" inside refresh-less custom blocks. I.e.:
```scratchblocks
when gf clicked
test

define test
broadcast [test v] and wait

when I receive [test v]
... // some script that takes even a short time to run (not necessarily refresh-less)
```
The "test" custom block will lag really hard even if the script under "when I receive test" is very short - so it seems like no-refresh custom blocks don't deal well with "broadcast and wait".

(If you're curious where I encountered this before, it was in my Text with Pen project where I tried to use broadcasts for each character and had to use "broadcast (letter) and wait". When the master block was normal, it worked fine, but if I tried to make it instantaneous it would lag hard.)

**Comment by TheLogFather** [comment]
Yes, it's well-known that you should never use a 'wait' type block within a non-refresh script (e.g. "ask and wait", "broadcast and wait", "wait until", "wait N secs") since non-refresh gets run atomically (i.e. it 'stops' all other scripts while it's running, so no other scripts get a look-in to change anything, meaning most of them would wait forever if Scratch didn't impose a half-second non-refresh limit).

But what @PiotrGrochowski gives above has only normal broadcast blocks, so it shouldn't cause any problems.

If the script is really this:

define test  (non-refresh)
broadcast [v test] and wait

...then I would expect the problem described, and it's simply a misunderstanding of how non-refresh works/behaves, and needs rewriting to take that into account.
(Though it'd be nice if Scratch could deal with it in some way...)

**Comment by PiotrGrochowski** [comment]
No! I simply didn't include that wait detail.

**Comment by TheLogFather** [comment]
I wonder if it's worth suggesting that a 'wait' inside a non-refresh script causes it to yield as normal, despite it being non-refresh? – I don't see an immediately obvious problem against making it behave that way...?
