### ISSUE TITLE
Timeout if using repeat block

### ISSUE THREAD

**Issue by SimaKyr** [LLK/scratch-flash#1358]
Here if to use some blocks for example: move 10 steps five times that there is no timeout, if to use the block to repeat that is a timeout. Why timeout? If possible, fix this. The project where this is shown:
https://scratch.mit.edu/projects/171368080/

**Comment by thisandagain** [comment]
Hi @SimaKyr we don't quite understand your question. Could you please clarify?

**Comment by towerofnix** [comment]
The reason there is a delay when using the repeat block is because often times people do want there to be a delay. For example, "repeat 10: change color effect by 25" -- people (and kids!) expect to see the color effect go up by 25, 10 times, not the effect instantly changing by 250.

If you want to make your repeat block have no delay like you described, you can make a custom block which is marked "run without screen refresh" and then add the loop to that. [See my remix.](https://scratch.mit.edu/projects/175803785/)
