### ISSUE TITLE
Stuttering sound plays if loading a project while another project (in separate tab) is playing a sound

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-flash#1399]
### The Problem

The sound stutters if you have a tab with a scratch project playing a sound and you simultaneously are trying to load a new project in a separate tab.

### Steps to Reproduce
1. Open a tab and navigate to a scratch project that plays a background sound for a while. This is the project I was playing when I found the bug: https://scratch.mit.edu/projects/151834588
2. Run the project. 
3. In a new tab, navigate to the scratch website and click 'Create' to open a new project.
4. Observe the sound stuttering while the new project is opening up.

**Comment by towerofnix** [comment]
I've seen this plenty before. I've always guessed the issue has to do with both projects running on the same Flash thread (for some reason). So whenever Flash is hanging - e.g. because of a big process in a single frame, like loading/creating a project, or just a long run-w/o-screen-refresh block - the sound stutters.
