### ISSUE TITLE
Missing translation strings in offline editor

### ISSUE THREAD

**Issue by nathan** [LLK/scratch-flash#450]
Separated from https://github.com/LLK/scratch-flash/issues/68 (for online).

- [ ] Open
- [ ] Save as
- [ ] Share to website
	- [ ] Share to Scratch Website
	- [ ] Project name:
	- [ ] Your Scratch name:
	- [ ] Password:
	- [ ] Upload failed
	- [ ] Your Scratch name is required
	- [ ] Success
	- [ ] Your project has been uploaded to scratch.mit.edu
- [ ] Check for updates
	- [ ] Update not needed
	- [ ] This is the current version.
- [ ] Quit
- [ ] Scratch 2 Offline Editor
- [ ] Save project?
- [ ] Don’t save

**Comment by 2jour** [comment]
Can we close @cwillisf?

**Comment by cwillisf** [comment]
Yep, as of this morning these strings are now available for translation.

**Comment by ntlrsk** [comment]
There are a couple of other translation strings missing from the online and offline editor:
* when Stage clicked  [it's not on translation server, and is commented out of the po file, I think because it was added to 2.0 later than other blocks]
* message1 [it's on the translation server within editor, but the translations aren't showing up online or offline]
I checked this in a couple of languages (Spanish, Danish).

**Comment by ntlrsk** [comment]
@2jour Can we mark this prio high? The two strings I added are in English right now in all languages.

**Comment by 2jour** [comment]
@ntlrsk  what is message1?

**Comment by ntlrsk** [comment]
@2jour "message1" is the default entry in these three blocks: "broadcast" , "broadcast and wait" and "when I receive" 

![image](https://cloud.githubusercontent.com/assets/4721032/9631997/76b56b6a-5152-11e5-89af-bb15cad50a15.png)

**Comment by 2jour** [comment]
nvm i see it :) .. yeah sure

**Comment by 2jour** [comment]
Moved to LLK/scratchr2#2785
