### ISSUE TITLE
Wrong error dialog box being thrown when logged-out user tries to save

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-flash#522]
User logs into scratch, creates project in second tab
Logs out of account in first tab
When attempting to autosave in second tab, network error dialog is incorrectly thrown:

https://s3.amazonaws.com/uploads.hipchat.com/52172/354199/9TZ13KXgNG8by5Z/Screenshot%20from%202014-10-29%2013%3A22%3A48.png

**Comment by jwzimmer** [comment]
When I follow @kaschm's repro steps, I am seeing both the message saying you need to sign in to save, and the message saying network is not connecting. Would it be possible not to display the network not connecting warning in this context, since I don't think it adds any helpful information from the user's perspective and might be confusing?
(Chrome 52, Mac OS X El Capitan, on Production)
<img width="942" alt="screen shot 2016-08-18 at 10 24 18 am" src="https://cloud.githubusercontent.com/assets/1320456/17777285/f9dbeb6e-652d-11e6-9fc3-9169d0af4b7b.png">
