### ISSUE TITLE
Flash menu showing instead of Scratch menu

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#523]
Context menu in the Scratch Editor is showing the Adobe options instead of the Scratch options.

Appears to be only showing up on Ubuntu/Firefox so far 

http://scratch.mit.edu/discuss/topic/61508

**Comment by doyousketch2** [comment]
This is happening on mine now.  Is there an About:Config setting we need to change?
Linux Mint Debian Edition 2 Betsy 64bit, Firefox Light 44.0, Flash 11.2 (release 202)

**Comment by doyousketch2** [comment]
Maybe it's because there's no 3D hardware acceleration on this video card..?

inside Scratch.as it looks as if it only allows the right-click menu if you have 3D enabled.

998     if (SCRATCH::allow3d) { // TODO: use a better flag or rename this one
999         // These events are only available in flash 11.2 and above.
1000       modalOverlay.addEventListener(MouseEvent.RIGHT_CLICK, eatEvent);
1001       modalOverlay.addEventListener(MouseEvent.RIGHT_MOUSE_DOWN, eatEvent);

However, I'm certain this can do right-click menus.  They are viewable on any of these demo pages:
http://www.actionscript.org/resources/articles/15/1/Context-Menus-in-Flash-MX-2004/Page1.html
http://stackoverflow.com/questions/9669369/as3-custom-contextmenu-to-children
http://www.uza.lt/2007/08/19/solved-right-click-in-as3
http://flexdevtips.blogspot.com/2010/01/flex-context-menus.html

**Comment by jwzimmer** [comment]
@chooper100 reported in https://github.com/LLK/scratch-flash/issues/1181:
> Right click bringing up browser flash context menu over scratch context menu
