### ISSUE TITLE
No longer works on Flash 11.3

### ISSUE THREAD

**Issue by rfinean** [LLK/scratch-flash#532]
Between 22 October and 5 November 2014 the live build on http://scratch.mit.edu/ changed from one that (mostly) worked on Internet Explorer 8 + Flash Player 11.3.300.265 to one that has two crippling bugs:

1. it fails to sign in and cannot save projects anywhere except download to local drive
2. the right-click context menu always displays the Flash Player menu, not the Scratch context menu.

I see that 89067bc16f7c1760621306a763a6b7ae8911392e (part of v426b) is described as requiring Flash 11.7 but the FAQ http://scratch.mit.edu/help/faq/ still claims Flash 10.2 is supported.

**Comment by 2jour** [comment]
@rfinean we are currently working on this issue

**Comment by kaschm** [comment]
@rfinean - we have some unfortunate news - we have decided to move up our IE8 deprecation timeline because the issues are too large and involved for our small team to handle. Additionally, we are preparing to launch SSL support, which IE8 on Win XP is not compatible with generally. Therefore, we are closing this issue. We apologize for the inconvenience :(

**Comment by rfinean** [comment]
OK, I understand. Our library updated to Windows 7 last week so the problem is finally gone for my code club. Please can you update the [FAQ](http://scratch.mit.edu/help/faq/#about-scratch) page? It currently claims incorrectly "To run Scratch 2, you need a relatively recent web browser (Chrome 35 or later, Firefox 31 or later, or Internet Explorer 8 or later) with Adobe Flash Player version 10.2 or later installed."
