### ISSUE TITLE
List casting inconsistency between 1.4 and 2.0

### ISSUE THREAD

**Issue by djdolphin** [LLK/scratch-flash#538]
In 1.4, a reporter for a list with the contents 1 and 2 (numerical values) would return '12', and a reporter for a list with the contents '1' and '2' (string values) would return '12' also. In 2.0, a reporter for a list with the contents 1 and 2 (numerical values) returns '1 2', and a reporter for a list with the contents '1' and '2' (string values) returns '12'. This was reported on the forums [here](http://scratch.mit.edu/discuss/topic/63378/).

**Comment by TheLogFather** [comment]
Should note this is still an issue:
https://scratch.mit.edu/discuss/topic/201798/

**Comment by TheLogFather** [comment]
How about this for primContents:

        private function primContents(b:Block):String {
                var list:ListWatcher = interp.targetObj().lookupOrCreateList(b.spec);
                if (!list) return '';
                var c:String = list.contents.join(' ');  // start by assuming delimeter is needed
                if (c.length == list.contents.length*2-1) c = list.contents.join(''); // check if it wasn't
                return c;
        }

I don't know the details of how ActionScript goes about returning Strings, so if c ends up getting copied to return it, rather than as a reference, then above could be bad. Also, if it ends up doing the join twice in mem, rather than re-using the mem for c on the second join, then that would be bad too...

But if it does both of those sensibly, then above code should mean most of the time it does a single join, and no longer needs to go through all the items checking if they have length 1.

**Comment by TheLogFather** [comment]
This is *still* an issue.

See https://scratch.mit.edu/discuss/topic/211913/ and see my post there for more details...

**Comment by jwzimmer** [comment]
@TheLogFather said in #1180:
> #538 is still causing problems:
https://scratch.mit.edu/discuss/topic/201798/
https://scratch.mit.edu/discuss/topic/211913/
