### ISSUE TITLE
Reporters inside Command Blocks that wait (Extensions)

### ISSUE THREAD

**Issue by Felizolinha** [LLK/scratch-flash#576]
If you have a reporter inside a command block that uses a callback, the command block repeatedly calls the reporter while it's active, instead of only once.

**Comment by cwillisf** [comment]
@Felizolinha, I'm not sure I quite understand the situation you describe. Could you provide a specific example, or perhaps a screenshot?
It sounds to me like you mean that if you have (for example) an "if" block that checks the value of a reporter, and that reporter is an asynchronous reporter provided by an extension, then the reporter's callback gets called each time the "if" block's condition is checked. That's actually working as intended: depending on the nature of your extension the value might fluctuate over time, and we'd like to collect the updated value when possible.
If that's not what you mean, please help me understand the situation so that we can help fix the problem. Thanks!

**Comment by Felizolinha** [comment]
Ok, I'll give a specific example. If you put a reporter block that waits for user input inside a command block that waits for another user input, the command block will keep calling the reporter until the user inputs the second value (e.g. pressing the button that calls back the command block).

If it's still not clear, maybe you can test it with this extension: https://monkeyguts.com/code.php?id=696 Put the confirm block (reporter version) inside the "Set clipboard to" block and see what happens.
* The extension requires a Userscript Manager.

**Comment by la10736** [comment]
My guess is that is the right behavior: you use `r` blocks and that is like sensors and so polled in asynchronous way. You should use `R` instead if you want implement a *one time for thread request*. You use javascript extension and `R` should work properly (in HTTP there are still some issues)
