### ISSUE TITLE
Strange behavior on evaluation by multiple agents

### ISSUE THREAD

**Issue by cslaviero** [LLK/scratch-flash#588]
Hello there,
 
I'm trying to build a simple version of the Dining Philosophers, which is available at http://scratch.mit.edu/projects/40307764/ . Each of the agents evaluates if there is a fork available in both it's "left" and "right" sides. If it sees both forks, then the "philosopher" takes them by hiding the sprites (using a message that only its left and right forks can listen). 

The behavior I expected was that only two philosophers would be able to get both forks, since there is not enough forks available to all of them. However, what happens is that all of the philosophers get forks, which in my perspective is not correct. When I run the code manually (by clicking in each philosophers' code to make it run), this behavior happens. 

What I'd like to know is whether this behavior is somehow correct, since from what I could read, Scratch has a sequential behavior when running a program. In my programming I could not find any mistake that could be related to this non expected behavior.

Thanks.

**Comment by TheLogFather** [comment]
I think I see the problem...

Are you expecting a broadcast to be received and executed immediately, before any other scripts get a chance to run? That's not the case...

What's happening is that the broadcasts get sent, but the Green Flag scripts all run before the receive scripts get started up.

It's only once all GF scripts have finished (and all costume switched) that the receive scripts get a look in.

Does that make sense...?

**Comment by cslaviero** [comment]
Yes it makes sense @TheLogFather :) So it's not a bug, it's a feature, that's good to know :) I've changed the evaluation to global variables representing the forks instead of checking if they are touching the philosopher sprites and it worked as I would expect. However I'm still wondering if this is the only way of doing it. Will this only be possible by using this kind of abstraction (variables representing the state of each fork)?

**Comment by TheLogFather** [comment]
I'd suggest you use broadcasts to control the sequence of execution more precisely.

In other words, have the Nth "philosopher" start its check when it receives "Check N" (where N goes from 1 to 5), and each one ends by broadcasting to start the next (and GreenFlag broadcasts to start the first one).

Or you could have a script that does "broadcast [Check 1] and wait / broadcast [Check 2] and wait / etc...", so it's getting each to check in turn, all sequentially.

(At this point I think we're really into what the ["Help with Scripts"] (http://scratch.mit.edu/discuss/7/) forum is for, rather than here...)

**Comment by 2jour** [comment]
@TheLogFather, thank you for your help.

I looked at the Dining Philosophers project, @cslaviero. @TheLogFather is right. His suggestions will help you control the flow for checking if a philosopher has a fork.

It looks like the issue is closed . @cslaviero, if you think that there is still an issue please reopen :)
