### ISSUE TITLE
Lists - Duplication of list data

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#591]
From @TheLogFather,  "It looks like list info is getting placed in the JSON twice - appearing as part of the stage, as well as whatever else owns it...  This causes unreliable saves of long lists".

**Comment by 2jour** [comment]
TODO add more description @2jour

**Comment by 2jour** [comment]
Also issue with uploading projects with long list https://scratch.mit.edu/discuss/topic/170384/?page=1#post-1635847

**Comment by thisandagain** [comment]
Adding `request` label to ensure we check this as a part of the implementation for 3.0

**Comment by TheLogFather** [comment]
Now that the JSON limit has been reduced to 2.5MBytes, this issue has become rather more acute, and people are running into it more often. –Any chance of a fix being looked at sooner than 3.0 release?
(I guess one of the big issues is backward compatibility...?)

**Comment by TheLogFather** [comment]
OK, just been having a look at this, and it seems to me that the main difference between variables and lists is that a variable is not the same as its watcher, whereas a list *is* the same as its watcher.

Now, variables are added to the JSON for sprite/stage here:
https://github.com/LLK/scratch-flash/blob/develop/src/scratch/ScratchObj.as#L592
And variable watchers for Stage are added here:
https://github.com/LLK/scratch-flash/blob/develop/src/scratch/ScratchStage.as#L839
And for sprites here:
https://github.com/LLK/scratch-flash/blob/develop/src/scratch/ScratchStage.as#L850

However, the lists are added to the JSON for sprite/stage here:
https://github.com/LLK/scratch-flash/blob/develop/src/scratch/ScratchObj.as#L593
But list watchers are also added for Stage and sprites in the same lines as above.

Since a the existence of a list already means the ListWatcher exists, isn't it simply a case of not pushing ListWatchers onto "children" in those two lines (839 and 850) – they've already been added in ScratchObj.as line 593.

I've experimented with simply removing the second instance of the lists from the JSON (which corresponds to not including ListWatchers as children), and it has worked for me so far...

**Comment by TheLogFather** [comment]
To summarise previous comment (if TL;DR):

I think the *really simple* fix is to NOT include ListWatchers in lines 839 & 850 of ScratchObj.as.

**Comment by TheLogFather** [comment]
(Oo-er... how to get rid of the multiple references above, where I messed up multiple times doing stuff with git/github in wrong branches, etc? –just for a change...)
