### ISSUE TITLE
Undo and redo in the workspace

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#625]
Dragging blocks in the scripts panel can go terribly wrong so I think we would need an undo/redo functionality in it just like in the image editor. They should maybe use the same undo queue?

**Comment by AndersBillLinden** [comment]
I have found the "undo" branch since I was writing this issue. I merged master into it and sent a pull request. Nothing yet.

**Comment by 2jour** [comment]
I propose we should bring this up at the editor meeting @kaschm

**Comment by AndersBillLinden** [comment]
When thinking about it, having separate undo queues for different editors is the easist thing both to implement and to use.

**Comment by ntlrsk** [comment]
I see how it could be useful, but unfortunately it is hard to figure out how to get undo and redo to do what people might expect, which is why we currently only have an undelete. For example, will it undo snapping together blocks? Will it undo dragging in individual blocks? Will it undo clicking on a stack of blocks (i.e., change the sprite's location on the stage)? Depending on what they are doing, they may or may not expect any of these.

**Comment by AndersBillLinden** [comment]
Undo should restore the last operation. If you moved a block A so it was snapped together with another block B, the undo operation should result in A and B being moved to their position before the operation.

**Comment by kaaloo** [comment]
I was expecting undo during a recent Scratch Day workshop we were hosting and unfortunately messed up a participant's script :(  This feature seems indispensable if only to avoid embarassing bumbling facilitators like me.

**Comment by ntlrsk** [comment]
I like the suggestion of an undo just for the script panel -- which would undo the script editing but would not undo anything with the sprites or Stage. Where could the buttons be? Within the script area - near the zoom bottom right?

**Comment by griffpatch** [comment]
Thumb up for this... Way overdue *grin*. We get by of cause, and perhaps it
makes us all the more careful ;) but when the worst happens, boy does it
happen!
