### ISSUE TITLE
add >=, <= and ≠

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#646]
I think it is necessary to add >=, <= and ≠.

**Comment by AndersBillLinden** [comment]
I agree!

**Comment by lize777** [comment]
Like this
![image](https://cloud.githubusercontent.com/assets/8316018/6370966/6fe706c8-bd31-11e4-97eb-40e44009c69f.png)

**Comment by ntlrsk** [comment]
It might be convenient, but also could look complicated to have all those options in the pull-down. It is possible to use the operators "or" and "not" to get those functions with the existing =, > , <.

**Comment by lize777** [comment]
@ntlrsk you are right, sometime look complicated

**Comment by AndersBillLinden** [comment]
I do not think it is too complicated. Those operators are understood by kids.

**Comment by AndersBillLinden** [comment]
I think there should settings to make the application more advanced.

**Comment by Felizolinha** [comment]
@AndersBillLinden I think extensions are already going to be a good way to make Scratch more advanced, but as they don't have access to AS functions it's still a good idea to include more advanced stuff.

@All I think it would look better if ≤ and ≥ were used instead of <= and >=. Of course little kids would need to interpret it a little bit more, but it's the symbol used in Math and they'll have to learn it someday :p

**Comment by AndersBillLinden** [comment]
I need to check how extensions in scratch work.
I agree that ≤ and ≥ are better because that is how teachers write it on the blackboard.

**Comment by lize777** [comment]
@AndersBillLinden Writing on the blackbloard is a good reason. I hope ge,le and ne is added in v433.

**Comment by AndersBillLinden** [comment]
I proposed an addition of this functionality with the pull request https://github.com/LLK/scratch-flash/pull/653

**Comment by AndersBillLinden** [comment]
What is a "triage" label?

**Comment by lize777** [comment]
@AndersBillLinden I also want to know what is label "triage".

**Comment by Sonickyle27** [comment]
I don't think this should be added as they all have simple workarounds that translate well to real programming languages.

**Comment by AndersBillLinden** [comment]
It wasn't very good looking actually, but I still think it is useful...

![image](https://cloud.githubusercontent.com/assets/1017466/6511422/13a329e0-c36d-11e4-8969-8df1dbd4f021.png)

**Comment by AndersBillLinden** [comment]
It was not very good looking, but I still think those operators are useful.

![image](https://cloud.githubusercontent.com/assets/1017466/6511430/2becccd6-c36d-11e4-85a4-743d1ccf4cec.png)

**Comment by serialc** [comment]
Triage refers to sorting or assigning. In this context it's more about deciding who/how this issue will be resolved. See https://github.com/codetriage/codetriage#what-is-triage

**Comment by ntlrsk** [comment]
I do think it makes it look more complex in the palette (on the left) and push down the boolean blocks which we want very visible. I agree with @Sonickyle27 that there are easy to read workarounds (using not, or). Perhaps there could be a pull-down for the <,  =,  > blocks in the palette to get the variants, so that they don't appear in the main palette. Though then people might accidentally choose them, and we've been trying not to have drop down menus with just two options.  Still that would be a compromise, which I'll discuss with others on the Scratch Team.  I do think the ones on the right aren't so clear (makes it look like small vs. big versions of < and > which could add to the confusion). As you can see, we're really careful about adding any additional blocks to the main palette areas.

**Comment by ntlrsk** [comment]
At the same time, we really appreciate the suggestions, and understand why it would be useful for those familiar with the symbols to have them readily accessible.

**Comment by cpseager** [comment]
It's also interesting to note that  'not =' sneaked in ages ago within the WeDo extension, as has the use of a drop down menu for >, <, = 

![not_equal](https://cloud.githubusercontent.com/assets/7423187/6618045/11a8058a-c8b7-11e4-8ef5-2a2b332441ed.PNG)

**Comment by AndersBillLinden** [comment]
@ntlrsk It is encouraging that you say that you appreciate the suggestion now when a lot of my suggestions have became unattended and unanswered.

**Comment by AndersBillLinden** [comment]
@ntlrsk The difference your encouragement makes is that I will maybe continue looking for fixes and suggestions.

**Comment by ntlrsk** [comment]
@AndersBillLinden we do hope you won't get discouraged! We have a small dev team and a rapidly growing project. We all do read every post here, just unable to respond to all right now, but they are all under consideration and appreciated.

**Comment by AndersBillLinden** [comment]
:+1:

**Comment by ntlrsk** [comment]
@AndersBillLinden and all, the editor team expressed concern about a drop-down menu in a block that has no other characters - as it may cause an issue when people try dragging the block, particularly in the upcoming tablet version. However, they agreed it would be good to add the three: "not =" ,  ">= " and "<="   to the context menu (i.e., the right-click/shift-click menu). And once the tablet is implemented, we can revisit the possibility of the other additions.

**Comment by ntlrsk** [comment]
@AndersBillLinden are you willing to implement the version with those three listed in the context menu? Many thanks!

**Comment by AndersBillLinden** [comment]
I changed the operators a bit, however, I cannot use `not =`, I had to name it `not=`.

![operators](https://cloud.githubusercontent.com/assets/1017466/6742159/c4c2e85c-ce8d-11e4-9758-65172a2aa7ac.png)

**Comment by ntlrsk** [comment]
Hmm, maybe using ≠  then would be better (even though it's different from the WeDo extension).

**Comment by cwillisf** [comment]
@AndersBillLinden, it looks like the test above might be using U+2A7D "LESS-THAN OR SLANTED EQUAL TO" instead of U+2264 "LESS-THAN OR EQUAL TO" (and their greater-than companions, of course). Maybe it would look good with the latter? Here are U+2264 and U+2265: ≤ ≥

I also wonder about the size of the not-equal-to symbol in that test... were you using U+2260 "NOT EQUAL TO" (≠) or perhaps something else? It wouldn't surprise me you were using U+2260 and Flash just rendered it oddly, but I thought it might help to double-check. :)

**Comment by AndersBillLinden** [comment]
I had used letters copied from google searches. `"\u2264 "`, `"\u2264 "` and `"\u2260 "` made no difference to the rendition.

**Comment by AndersBillLinden** [comment]
Ok, what now?
