### ISSUE TITLE
Could Scratch add Chinese font?

### ISSUE THREAD

**Issue by lize777** [LLK/scratch-flash#657]
I am a one of admins of MaoYouHui(it is biggest Scratch community in China).
Recently, more and more teachers are asked to add the Chinese font in paint editor, like "mBlock":
![123](https://cloud.githubusercontent.com/assets/8316018/6500835/da7509ca-c34b-11e4-955e-2a75f39b15d5.JPG)

**Comment by lize777** [comment]
“楷体” “宋体” “微软雅黑” "黑体" “圆体” are Popular.

**Comment by ntlrsk** [comment]
Yes, we really need a way for non-English fonts to get added, and there is another Github issue about this. It is helpful to hear which Chinese fonts would be useful. The difficulty is that every time we add a font the size of the Scratch site becomes much bigger and therefore slower to load. So we are planning to a add way for you to add any font from your System into Scratch, so that it would work for any language.

**Comment by ntlrsk** [comment]
I will close this for now, even though it is important, it is addressed by this issue: https://github.com/LLK/scratch-flash/issues/231
