### ISSUE TITLE
[Offline Editor] Wedo Motor does not Execute blocks after Wait .5

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#673]
version 434

OS x 10.10
Not sure if this is found in v433

download http://scratch.mit.edu/projects/46483968/ and run

You will notice only the block before the wait is executed

Works for wait 1 second but not wait .5 second

**Comment by 2jour** [comment]
This exists in offline editor v433.. @cwf this is not a priority to get this into the upcoming release. Let me know if we should take out.

**Comment by ntlrsk** [comment]
@2jour Does 0.5 work (that is, adding the leading 0?) Thanks.

**Comment by cpseager** [comment]
@2jour This is because the wedo extension is currently programmed with an exact 500ms 'coasting time' after a motor switches off (function okayToReadIDs() in the js). However there are still some dodgy times around about the 0.5s mark that can stop the next 'motor on' working correctly.

Change your delay to .7 (longer than the motor coasting time) or even .3 (protected by the current 500ms timeout) and it should work ok. 

The solution may be to be increase the 500ms slightly, or to use active braking instead of coast braking. Active braking actually works quite a lot better for some WeDo models such as the alligator and fairground rides, but will need a rewrite of the js.

**Comment by 2jour** [comment]
Thanks @cpseager :) .  I will try them

**Comment by cpseager** [comment]
As .7 always works for me, but .65 was still unreliable I changed this line in the wedo extension from 500 to 700. All delays now work as expected for me. This simply means that the motor ID reading was unreliable up to 700ms after motor switch off, not 500ms as currently programmed.
 

        return (new Date().getTime() - motorOffTime) > 700; // was 500

**Comment by 2jour** [comment]
@cpseager yep you are right 

wait .39 works 
wait .6 works
wait .7 works

not wait .5 :)
