### ISSUE TITLE
Buttons isn't show in Paint Editor in unEnglish langs

### ISSUE THREAD

**Issue by dimon4ezzz** [LLK/scratch-flash#682]
![2015-03-29 17 36 06](https://cloud.githubusercontent.com/assets/4592929/6885451/44952276-d63a-11e4-9c65-ad004eed12e8.png)
Buttons “Set costume center” go under right side
E.g. in Indonesian or Russian

**Comment by ntlrsk** [comment]
I wonder if this is due to the addition of the crop button.

**Comment by 2jour** [comment]
In German the flip across x axis is cut off too

**Comment by cpseager** [comment]
@ntlrsk It's simply because the 'clear' button has longer text and so is a longer width button in those languages. You can duplicate the problem in English by just dragging the browser right hand edge inwards to reduce the editor width, the right hand buttons then start disappearing out of view..

English is generally one of the 'shortest' languages in terms of text length, for instance German phrases are generally much longer than English.

Changing clear/add/import to be only icon buttons (with tooltips) would help considerably.

**Comment by 2jour** [comment]
I still can't see the centre button for the costume editor on my port when i set language to russian
