### ISSUE TITLE
Project inactivity

### ISSUE THREAD

**Issue by AndersBillLinden** [LLK/scratch-flash#688]
I have 7 pull requests that have not rendered any comments/reactions.

And some more where I actually got a response but after that they died out.

One of them being a pull request that addresses a shortcoming in scratch (cannot rename lists) that has made people starting 6 scratch forum threads. Some of those messages are from Nov 2012. https://github.com/LLK/scratch-flash/pull/640

I have one pull request where I have been asked to alter my code. I have suggested a solution but got no answer. https://github.com/LLK/scratch-flash/pull/654

I give this project one more week, if my changes are still ignored after that then I will remove my pull requests.

**Comment by cwillisf** [comment]
@AndersBillLinden, I'm sorry you feel frustrated, but this is not an appropriate use of the GitHub issues mechanism.

Please be assured that we do welcome contributions from members outside the team, but there are two reasons that we have not yet accepted your recent pull requests.

First, we are working to resolve a policy issue regarding contributions from outside the team, and until that issue is resolved we will not be able to accept any such pull requests. This matter should be resolved in the very near future, perhaps in a matter of days. Once we have the solution in place we will contact you and other contributors directly. After that we will be able to merge, for example, #640.

Second, as you may know, we are a very small team with limited time and so we must focus on our priorities. While renaming broadcasts (#654) is a very welcome feature, for example, it is not one of our top priorities. Each individual and sub-community has a different set of priorities, though, and that's a large part of why we opened the core Scratch source code to the community: so that members of the community can help us address their own priorities in addition to the team's priorities. In principle, both #640 and #654 are excellent examples of this idea in action. @sclements, one of our lead developers, requested some changes to #654 / AndersBillLinden@9a2225a to match our standard practices. If you make those changes then we would be happy to merge #654 once the policy issue is resolved.
