### ISSUE TITLE
Comparison of large numbers

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [LLK/scratch-flash#707]
As I posted about a while ago on the forums, Scratch fails to correctly test 2 large numbers for equality unless they are both prepended with a string to force string comparison. Scratch should be doing this by itself.

The problem is, the primitive comparison only [tests if casting to a Number returns NaN or not](https://github.com/LLK/scratch-flash/blob/d0fdaa101f88c4c0d3bc956d94cc5c6733845db2/src/primitives/Primitives.as#L150), when the interpreter could have actually [truncated the end of the number](https://github.com/LLK/scratch-flash/blob/d0fdaa101f88c4c0d3bc956d94cc5c6733845db2/src/interpreter/Interpreter.as#L379).

For example:

``` actionscript
    Number("1234567892345678923456789234567892345678923456789")
 == Number("1234567892345678923456789234567892345678923456788")
```

returns true because Number truncates both to

```
1234567892345678900000000000000000000000000000000
```

To fix this issue, an additional comparison needs to be made

``` actionscript
var numberAsString:String = ...;
if(!(numberAsString.indexOf(".") > -1) // it's a decimal; not much you can do I guess...
        && Number(numberAsString).toFixed() != numberAsString){
    // compare args as strings instead of numbers
}
```

**Comment by TheLogFather** [comment]
There are quite a number of rather subtle difficulties associated with trying to 'fix' an issue like this.

The basic problem comes about because Scratch attempts to hide the concept of variable 'type' from those who may easily be confused by meeting such a concept so early in their coding experience.

Unfortunately, there are a number of places where the edges between string type and number type become rather unclear - even potentially unresolvable in general. Attempting to 'patch' such issues is usually a case of guessing the most likely use-cases and giving the expected results for those, as you have done above.

However, such 'fixes' often rely on assumptions about the intentions of the coder, and I suspect there could be times where such assumptions are not correct. In such cases, it may become even more difficult for coders to understand why Scratch behaves in the way it does, and how to make it work as intended, because Scratch jumps through various 'hoops' under certain circumstances, and these hoops and circumstances are unknown/ill-defined unless you're willing to investigate the Scratch source in detail.

As an example, off the top of my head, for your case above, what happens if someone tries to use some kind of time-stamp within their strings of digits, and then compares the two long strings of digits using > or < operators to check if one has happened 'before' another according to the time-stamp? (Let's assume that all the digits before the time-stamps would be the same because it contains, say, the encoded username, and you're comparing two events for the same user.)

For these operators, then, the values are treated as numerical (because you only patched = operator above, not > and <). If the time-stamps create differences at more than ~15 digits into the strings (which would likely be the case if the username is encoded into the data before the time-stamp), the values are truncated to be the same, so both of < and > will give false. Yet the equals operator also gives false because you did patch that. -So we have a situation where these three comparisons are saying something rather contradictory (a>b is false, a<b is false, a=b is false - huh?!)

No doubt you would suggest also 'patching' > and < in a similar way. However, I can assure you that leads to some potentially serious issues because the behaviour of > and < can be different when comparing two things as characters vs numbers. (i.e. a>b may be true if a & b are assumed numerical, but false if considered as character strings...)


I guess I'm kinda saying that having a well-known and fairly easy-to-understand boundary is actually simpler to deal with  (we just explain to coders to "join a character to both sides if you want to compare as strings rather than numbers") compared to a convoluted boundary that leads to a potential minefield of ill-understood and hard-to-explain behaviour...

**Comment by MegaApuTurkUltra** [comment]
You make a good point, however I'm pretty sure string comparison of numbers works the same way as numerical comparison, since byte values increase with character "values." I'll have to test this later (but it seems to hold true on pixie)

**Comment by TheLogFather** [comment]
Try it with negative numbers...

**Comment by MegaApuTurkUltra** [comment]
Good point. I think my problem with this is that the current equality operator did not give me expected results when I tried comparing numbers for my cloud data engine (I mean 2 numbers that are clearly not equal...are equal?!) and it took me a long time to track down the problem. I'm worried about its impact on other people who encounter it and may not be able to determine the cause.

I don't want to suggest that the current system should stay, but now I don't really see a solution

**Comment by 2jour** [comment]
Hi sorry for the late response .. I am going to propose that this be brought up at our editor meeting @kascm @cwillisf
