### ISSUE TITLE
Slowdown When Rotate

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#750]
OS mac osx 10.10.2
Browser : Safari
Reporter: Bugs and Glitches

This project demonstrates that rotation is very slow as opposed to goto
https://scratch.mit.edu/projects/60731652

https://scratch.mit.edu/discuss/topic/112922/

Workaround :  performance is noted to be better when using Stage3D

**Comment by griffpatch** [comment]
The slowdown is just a result of how scratch makes use of flash. Whenever
you change the costume for, resize or rotate a sprite, the sprite is
re-rasterized (converted to a bitmap) at the required resolution to be
drawn to the screen. Complex vectors take much longer because resizing a
bitmap is easy, but a vector needs all it's lines, polygons & fills
redrawing every time. Once the sprite is rasterized, it can be moved around
using goto with little to no expense because it does not need to be
redrawn, just pasted to the screen in a new location (this is called bitmap
caching).

It is worth noting that perhaps the 3d hardware mode using hardware sprite
rotation and keeps the originally cached bitmap unchanged? But that is just
a guess to explain why it would be faster as I have not looked at the 3d
rendering path in scratch.

**Comment by TheLogFather** [comment]
@griffpatch: yes, I thought that too - but the OP suggested in the topic that it wasn't always so slow if there was no touching test happening during the same time.

That made me wonder if there was something going on with caching the bitmap - since it doesn't actually need to cache it if it doesn't have to get all the pixels right for a collision test, or stamp it. (Presumably, Flash just has to stick the object on the screen in the right place, so Scratch doesn't need to make its own bitmap.)

So I went back and checked... and it's definitely slower now!

Something happened after v423g which had a detrimental effect on rotation.
But, looking at the changes for v424, it's really difficult to see what could be causing it... I'm suspicious that the change might actually have been something slightly earlier in github, that is related to bitmaps, after ~423f, but which wasn't really included in the v423g release...?

**Comment by TheLogFather** [comment]
A bit more info...

https://scratch.mit.edu/projects/60472556/ is a good test project to for this, so I did some experimenting.

There's a clear slowdown from v423g to v424 (as retrieved from djdolphin's Scratch archive - should really checkout from github to compare...)

But the crucial data point is that if I add a touching edge test in there then v423g becomes as slow as v424 - which is basically what the OP claimed in the discussion topic...

**Comment by griffpatch** [comment]
Nice work there :)

**Comment by 2jour** [comment]
agreed :) thanks @TheLogFather

**Comment by TheLogFather** [comment]
I forgot to link to the actual change I suspect may be causing it:
https://github.com/LLK/scratch-flash/pull/447/files

I checked if this change was really in 423g, and it appears not (despite the bump to 423g happening after it), but it is in 424.

The way to check is to create a large transparent rect around the sprite, and put "when this sprite clicked / say [hello] for (2) secs" The above change meant transparent objects were no longer included in the hit region, hence the clicks don't register on the transparent rect. Up until that change, they did.
