### ISSUE TITLE
New Block Suggestion: Stamp [Costume Name]

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#764]
At present, stamping costumes is a very expensive operation in scratch due to it having to re-rasterize the costume for the stage, stamp it and then revert the cache back to the original costume size. Also, this is combined with the user switching costumes manually and triggering re-rasterizations that are never then used. A suggestion I have is to add a new block "Stamp [Costume Name]" that would be an optimised version of stamp that does not interfere with the usual bitmap cache and does not result in the 'real' sprite's costume being changed.

**Comment by TheLogFather** [comment]
This could be a useful optimisation in some cases. It'd be "stamp costume [dropdown v]", I guess.

I wonder how expensive (memory-wise) it would be to have Scratch keep a copy of the bitmap cache for each costume that's been switched/stamped? -So, move the cachedBitmap from ScratchSprite into ScratchCostume. That would mean there's no need to rebuild it next time it switches to that costume or when stamped again (assuming it hasn't rotated, resized, etc.)
I guess there could be a limit to how big it allows such a cache of bitmaps to grow in total (so it would need to keep a list of all such bitmapCaches) - and once it passes that limit, then it starts to drop the oldest ones from the list...

Having said that, it just made me realise that if the above did happen automatically, it would mean there may not be quite so much point having this new block, since a costume switch would be almost free... :/

**Comment by griffpatch** [comment]
I've always thought caching of costumes rather than sprites would be
awesome, but only if it worked say by costume hash? You wouldn't want the
same costumes caches duplicated across clones! That then makes the problem
of different sizes and angles much more involved. Think paper minecraft, it
has hundreds of costumes on a single sprites duplicated across 200 clones.
But then a few of them draw at slightly different sizes... Hmmm
