### ISSUE TITLE
[Comparison Operator] constructor < a Returns True

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#773]
Reporter: https://scratch.mit.edu/discuss/topic/118662/ bugs and glitches
OS: mac osx 10.10.2
Browser: Safari

1. Go to project and play https://scratch.mit.edu/projects/64064376/

Expected: Bat should say false after it says 'constructor < a' . Bat says true because comparison operator returns wrong results

**Comment by TheLogFather** [comment]
For reference, it appears that the string "constructor" is equivalent to a string that begins with "[class ", followed by some upper-case letters (e.g. "[class SOMETHING]"):

"[class @" < "constructor" < "[class ["

In ASCII, the only characters between "@" and "[" are the upper-case letters (which Scratch turns into lower-case in strings, so we can't narrow it down any more so easily...)

It also doesn't happen if any of the letters in the string "constructor" are made upper-case (e.g. "Constructor"), which leads to the curious result that "constructor" = "Constructor" is false (which should be true in Scratch, since it's case-insensitive).

**Comment by 2jour** [comment]
Thanks for the info @TheLogFather  :)

**Comment by TheLogFather** [comment]
It's to do with the Dictionary class on line 149 of Primitives.as: https://github.com/LLK/scratch-flash/blob/a0be4e27766a243fcad6d8113f60cda529f1e6ac/src/primitives/Primitives.as#L149

The actual value of the string "constructor" is "[class Dictionary]".

Does using a Dictionary like this help the performance for the conversion to lower-case?

**Comment by TheLogFather** [comment]
It turns out that all methods of Dictionary, including those it inherits from Object, also show the glitch.

So, besides "constructor", the following strings can compare incorrectly:
"toJSON", "hasOwnProperty", "isPrototypeOf", "propertyIsEnumerable", "setPropertyIsEnumerable", "toLocaleString", "toString", "valueOf"

**Comment by TheLogFather** [comment]
Looks like this is relevant:
http://twistedoakstudios.com/blog/Post925_unfathomable-bugs-4-keys-that-arent
:/

**Comment by TheLogFather** [comment]
BTW, is there any reason not to just use an Object rather than Dictionary?
From what I've read as I looked at this, it seems like the the only reason to use a Dictionary would be if the keys may not be strings. But an Object works fine if all the keys are strings (as they are here), and appears to have slightly better performance...?

**Comment by sclements** [comment]
Well, the way I'm using it now would mean we could switch to an Object.
However, maybe I shouldn't be converting and prefixing non-strings. I'll
change that code to only prefix Strings which will allow us to keep using
the Dictionary properly (using non-string keys when appropriate). Sometimes
it can be expensive to convert things to strings.



On May 28, 2015, at 19:06, Aka DadOfMrLog <notifications@github.com> wrote:

BTW, is there any reason not to just use an Object rather than Dictionary?
From what I've read as I looked at this, it seems like the the only reason
to use a Dictionary would be if the keys may not be strings. But an Object
works fine if all the keys are strings (as they are here), and appears to
have slightly better performance...?

—
Reply to this email directly or view it on GitHub
<https://github.com/LLK/scratch-flash/issues/773#issuecomment-106646043>.

**Comment by TheLogFather** [comment]
Oh, ok, so is there anything other than strings that can get in here? - I hadn't actually noticed that it's a1:* & a2:*. (Also, I haven't really looked into how bools are dealt with in Scratch - but they essentially turn into 'true' and 'false', when viewed as strings, right?)

As I looked at this bit of code, I was also wondering if it'd be worthwhile making a separate chunk of code for the equality operator which checks the length of the strings before doing the conversion. I don't know how much of an optimisation it would be, but it feels like it's such a simple thing to do that it'd be worth exploring...

**Comment by sclements** [comment]
Alright, this should be the proper fix now and perform as well as it can. @2jour I can get you a SWF to test with.
