### ISSUE TITLE
Detect Connection State to Cloud Server (feature request)

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-flash#778]
Would it be possible to flag up connection issues with projects that use cloud data? Either an onscreen warning icon / text could be present at all times when a cloud scratch project is playing, but the cloud is not connected (perhaps on the bar with the green flag). Or a new block reported could be added that provides the scratch project with a connection status (connected, disconnected).

Games and projects that make use of cloud data 'often' are not able to connect due to 'new scratcher' status or get disconnected mid game (either because they go and check a message that popups up mid game and it happens to take them to another tab with the same project in... which disconnects the original one, or for some other reason!). But the upshot of a disconnection is that the user who 'is' a scratcher will have their save games / scores silently ignored or will find themselves suddenly playing alone, as the scratch project cannot detect the disconnect mid game.

It is also worth noting that the disconnect can sometimes appear one directional, where a user can see changes, but is unable to post changes back? I'm a little less sure about the credibility of this statement as there could be other underlying reasons, but thought it worth noting that I'd consider that a disconnect too.

**Comment by TheLogFather** [comment]
Yes, seconded - cloud could really do with something that helps make it more robust!

There were some suggestions here: https://scratch.mit.edu/discuss/topic/64346/

One of those was a suggestion by drmcw for a hat block "when [cloudvar v] changes".
The important feature of this is that it only gets 'triggered' by a change that comes from the cloud - i.e. local changes to 'cloudvar' don't count. -That means if you do change it locally, you can then tell whether or not a change made it to the cloud (within some reasonable time window).

**Comment by TheLogFather** [comment]
I've been thinking about this some more, and I realised that "when cloudvar changes" wouldn't provide for one particularly useful piece of info...

When a project first loads, it'd be really useful to know how long ago a cloudvar last changed. This provides a way to tell if a player's stats, within a cloudvar of a multiplayer game, are no longer relevant - most likely because the player left abruptly and the project didn't get chance to clear up properly.

My personal favourite of the suggestions, then, is Zro716's "time since [cloudvar v] changed". I guess that could be implemented through some form of time-stamp placed in the server's push of cloudvar updates to a project. (The important thing is that the project only gets that time info *from the server*, not from it's own knowledge of the changes it has made to cloudvars.)

Failing that possibility, my original suggestion of a "cloud timestamp" block would still be enough to implement something like above in a project (by including the time-stamp info in the relevant cloudvar values themselves, and so being able to compare those against the most recent time-stamp received by the project).
