### ISSUE TITLE
Global Procedures

### ISSUE THREAD

**Issue by bobbybee** [LLK/scratch-flash#782]
See https://scratch.mit.edu/discuss/topic/12015/?page=1

7 pages of supporters <3

Basically, like there is a check box on 'define a variable' to make it accessible from either this sprite or everywhere, procedures should have the same 'checkbox'.

If this is already on the tracker, I apologize; I didn't want to read through 150 issues to see if this is a dupe.

**Comment by bobbybee** [comment]
Any update on this? :/

**Comment by ntlrsk** [comment]
This change would have more complicated implications than simply ticking a box. One big issue is that a global procedure can only have one definition - so where would that definition live, and how would you prevent it from being defined in more than one sprite? How would you find it if you were in one sprite?

**Comment by ntlrsk** [comment]
To elaborate more -- The Scratch editor design team discussed this extensively when planning for Scratch 2.0. We all agreed that global procedures would be great to have and an important concept, but also recognized the challenges of adding it in a seamless way. If we had a separate block definition area that would add complexity to the Scratch interface and model (including when reading others' projects), which is not ideal. If we kept the definition in the sprite scripting area, it wouldn't be easy to figure out which sprite it would be in, and the difference between local and global definitions could get confusing too. 

A possible workaround, which would be a simple addition to the current model is the idea of being able to right-click on a define script (e.g., "define dance") and update all the define scripts with the same name in any other sprite. They would still be local definitions (and thus easy to see and change) but at least a way to update them all so they're the same. Thoughts?

**Comment by bobbybee** [comment]
Perhaps the cleanest way would be to require global custom blocks to belong to the stage instead of a particular sprite? The right-click method also seems viable, although I feel like it might be confusing if a new Scratcher forgets to update the definition, and is confused why it's not working on another sprite.

Alternatively, if a block is defined as global, it could be in its own area internally (in the JSON/memory/where-ever else), but to the user facing side, it appears like an omnipresent script, editable from every sprite

Although even that would be confusing... ahh!!

**Comment by ntlrsk** [comment]
Yes, you see the issues... And one of the issues with using the Stage (although it's shared) has no motion blocks (since it can't move).

**Comment by TheLogFather** [comment]
This is something I've been pondering for well over a year now - it always sounds so simple when the suggestion is put forward again and again in the forums, but it clearly isn't. -So many questions about local vars, UI, etc...

The only vaguely-decent solution I've managed to come up with is an option in the 'Edit block' dialog to "Share across all sprites" (which I guess might include the stage**, since that just ignores irrelevant blocks, like motion/direction/etc...)

When that new option is checked, the script then appears in *all* sprite editing panes, as if it was copied there (who knows exactly in what position it first appears - I'd guess it starts off either at top-left, or in same position as sprite where it was originally created - and I expect it should be allowed to be moved independently in each sprite thereafter).

It seems like editing that script and definition should affect the script and definition in every sprite - i.e. they are 'linked' across sprites.

So far so (sort of) good...

But there are some obvious questions...
A couple of examples: What happens with local vars? (I guess it could be up to the user to ensure the vars are either global, or they are the same across sprites that actually call the script?** -but it could easily cause confusion.) What happens when this "Share" option is *un*checked? (Should it go back to only the sprite it was originally written in, or the current sprite from which the 'edit' was chosen?)

** Note that there is a tricky situation here with local vs global vars when the stage has a copy of the define script - if that script contains local vars, and the stage runs it, then *it will create global vars with the same names as the local ones*. This causes Scratch to get horribly muddled in various ways... :(

An alternative, which mitigates above questions/issues a little, but which is somewhat more complicated, would be to have the option to choose exactly which set of sprites to share across.
But then I guess it's not so different to just copying the script manually across sprites, and forcing it to be 'linked' when editing its spec - so maybe why not just do that...?

**Comment by TheLogFather** [comment]
> A possible workaround (which would be a simple addition to the current model) is to be able to right-click on a define script (e.g., "define dance") and update all the define scripts with the same name in any other sprite. They would still be local definitions (and thus easy to see and change) but at least a way to update them all so they're the same. Thoughts?

Actually, maybe there is a way to do something like this, and make it clear(er) what is happening...

How about this... if Scratch detects there is another sprite with the same definition, it gives the 'Edit block' dialog an extra checkbox "Copy changes to all sprites with this define script" (or something)?
Once that checkbox is checked, it remains checked whenever editing the same definition from other sprites that have it (until it's unchecked).

That way there is a means to choose which sprites have the script (copying manually), but, if you do happen to have the same in different sprites (e.g. you've duplicated it, or uploaded from disk, or whatever...), it doesn't assume the definitions are linked unless you tell it - so the default behaviour remains as it is now, which is often A Good Thing...

**Comment by miniluigi008** [comment]
If the option to share globally is unchecked, it could just convert all of the the custom block definitions that were being shared to local shares (if they are being used in that sprite.) If it's not being used in the sprite it can just delete itself.

**Comment by haverdude** [comment]
I cannot believe smart people are having this discussion.
Why not have a "super sprite" (class) that you can then derive a (subclass anyone?) a specific sprite from.  Put all the common code and data in the super-sprite, differentiate when creating a new sprite.  

You could even make the simple act of deriving a sub-sprite ask the user to define all the default variables and settings as defined in the super-sprite.

If the implementation is holding the project back from being able to implement, and therefore **teach**, these very important concepts, then the implementation is **wrong**.

I have worked with many, many programmers that were smart, but they just didn't grok the concept of code re-use and object orientation.

I actually studied computer science before object orientation was a thing - but we did have data structures, and even back then, getting the model right was job number one.  If you accurately model what it is you're trying to implement, you are not fighting the model to get the job done.

I don't see why introducing such a concept or something like it would not be a problem if it was introduced in such a way that you didn't have to know it right off the bat.  In that way, it's still accessible to newbies, but gives them somewhere to go when they start getting good at it.  If there's sprites, and then there's super sprites, and sub sprites, and you don't introduce super/sub sprites until later, then "problem solved' IMHO.

Just my two cents.

**Comment by bobbybee** [comment]
"I cannot believe smart people are having this discussion." Please be kind.

And yes, "smart people" have considered this proposal, among several others. It, too, has its shortcomings.

**Comment by TheLogFather** [comment]
Sorry, this is rather long, and probably a bit of a rant, and it may not be entirely obvious how it's related to this topic at the start... but I hope it has some things worth thinking about contained somewhere within it!

I think one of the problems I've seen come up fairly often is that 'seasoned coders' seem to consider Scratch as mainly there to teach "how to code". In particular, how to code with modern computer languages. I've seen it in multiple forum posts, not only from older Scratchers ("Scratch needs to do X Y Z to help teach how we code these days"), but also from others who started on Scratch and are now growing up and learning 'grown up' languages (posts like "why doesn't Scratch work like language X?").

Teaching such concepts is certainly no bad thing to do, of course, but as I looked at more and more projects shared by younger and younger kids, I came to the conclusion some time ago that it really isn't what Scratch is good for. Indeed, it's not even that good an idea to *try* to teach such things with (only) Scratch, because, in so many ways, it has such a different paradigm to modern coding languages – it simply isn't a fit tool to fulfil such a role by itself!

OK, so what *is* Scratch good for? Well, I think it's something that is rather more fundamental to coding, and something that younger kids need to start to learn before worrying about the kinds of modern programming concepts that us 'seasoned coders' tend to think are so important.

I don't know if this is a good description, but what I think Scratch teaches – what it is best suited to teaching – is how to think 'algorithmically'.
It's not something that comes naturally to young kids, and it's worth taking into account when considering how to (re)design (new) features into Scratch.

Also, I really think it's no bad thing that Scratch has such a different paradigm to modern coding. I think the fact that these older kids, who have moved on to other 'grown up' languages, can come back and *appreciate and grasp the differences* (as shown in their forum posts) is actually quite exciting. It means they are not 'bound' by the constraints of thinking in a certain way to get something done (even though it slightly worries me that they give the impression Scratch is 'doing it wrong' – I hope that's just the temporary excitement of having learnt something that they feel is more 'grown up' than Scratch).
It may mean that the next generation of coders could end up being more flexible in what they do than many of us 'oldies', because they are able to take each tool they have to hand, and see more clearly how to use its specific paradigms to the best advantage, rather than expecting to use it a certain way. (That is, just as long as us old fogeys don't hold them back by making them think they should really code all the time with the concepts and ideas that were invented in our time and we've grown used to...)

----

As an aside, I've found it interesting to watch, from time to time, as 'seasoned coders' try to do things with Scratch in a way that 'fits' with the concepts they use for modern coding – for example, treating sprites as if they are classes...
"Hey, my game needs multiple things that can each shoot, and it needs multiple bullets firing from each shooter. Obviously, I should make a different 'class' for each, and create 'instances' of those... So that's a sprite for shooters and a sprite for bullets, creating clones of each as needed..."
"Now... how do I instantiate a bullet so it fires in the right direction from the correct position of a specific instance of a shooter...? Hmmmm... global vars... broadcasts... yuck! This isn't like 'real' coding, is it..."

Well, no, it's not – and that's the point!

In case you're wondering, the 'mistake' was right at the start when equating sprites with classes, and therefore concluding shooters and bullets had to be separated. Thinking in such a way simply isn't a good fit for working with Scratch, so it's a mistake to try to make it work like that. (And, especially, to try to teach it as if that's what it's designed for!)

**Comment by bobbybee** [comment]
@TheLogFather FWIW, I'm one of these older kids, and I agree completely with your sentiment :smile:

**Comment by LFP6** [comment]
Definitely agree that getting this to fit is a critical issue. I recently posted [my own lengthy thoughts on OOP in Scratch](https://scratch.mit.edu/discuss/topic/110136/?page=3#post-1924907), which winds up being pretty closely linked to this discussion. There's some more detail in the topic, but here's the tl;dr (albeit pretty long still, it's clearer):

I don't think the issue is the inclusion of complex concepts in Scratch, but the fact that many people attempt to treat these concepts like Scratch was a normal text-based language and see nothing wrong with that, or see that as the only option and shut down the idea entirely. Looking at it this way just doesn't work, and there needs to be an effort to create solutions that fit within Scratch's paradigm. In my mind, code maintenance & organization in general are two of the biggest barriers in Scratch, and definitely a hard problem to solve in a way that fit the paradigm. Here's my own ideas for solving that:
* Collapsable blocks (for hats and C blocks), acting like collapsible code blocks, could significantly help the naturally "long" nature of Scratch code (not in the post linked above, I'll need to find the forum post for this, will edit later). This would relatively natural and low-profile.
* Broadcasts directed to a specific sprite would allow for global procedures in a way that mimics real languages (where you need to either call an object, or "include" it, which I'll get to in the bullet after next), and is generally cleaner (covered briefly in the topic, again will need to find the original post).
* Allow for creating multiple 'scripts' per sprite. The basis for my other ideas, this would fit easily within the existing UI, being that this is already how sounds and costumes are handled, and would help organization in its own right.
* Add script links. This is similar to what @TheLogFather proposed, but instead of including the block, you would get everything in the 'file' (see above), acting similar to components in Unity (which is pretty intuitive and clean IMO, why I'm suggesting a similar concept)
* What I'd like to see personally is an asset-based workflow, where you create scripts/images/sounds and then assign/link them to sprites. This resolves some awkwardness with "where am I linking from?" and just gives things a nice home. This would coexist with sprites (so you have your sprites and the assets defined within them), and then your "asset libraries" (come up with some approachable term for it). Linking is the key, but I would try testing this out to see if giving the option would wind up not being too confusing (I think it just needs the right presentation)
* Inheritance/Polymorphism could be pretty easily implemented by just creating a copy and having some visual indicator that it was inherited or overwritten, with something showing (possibly choosing) the parent. I doubt this would have a huge usefulness though, with the other things having a much more significant impact, but figured I'd mention the concept.
* Would be great to have an option for sprites to not start out instantiated in the scene by default. Doubt this would have a big impact, as users would primarily encounter it only if using it, and could be handled like visibility.
* The option for the green flag/stop to act like play/stop, with a clear indication of whether it's active, and then reset once it's done. Again, invisible unless used, but saves a lot of frustration, personally speaking trying to work with it (again, not in the topic, but applicable, will try and find).

And of course it's entirely possible these aren't the right approach. However, I would love to hear some thoughts if I'm approaching it in a way that could work.

**Comment by chooper100** [comment]
@LFP6 
My thoughts:

- Collapsible blocks: Sounds good; could take a while to implement though
- Broadcasts to a specific sprite: Again, sounds good although we would need to clear up whether clones would also receive that broadcast

From there on I think the ideas get a bit complex. Although seasoned programmers might understand asset libraries (and all that other fun stuff), we have to remember that a large number of 9 year olds (and some even younger) use Scratch. Also, imo the way assets work in Scratch currently I think is quite neat and extremely clear for young children.

**Back to general discussion:**
Personally, I think if the stage was allowed local variables, custom blocks in the stage should be made global. Then, they would be executed in the stage. (This would be clear due to the fact that there are stage specific blocks and the stage has certain limitations that sprites don't.) Doing this would potentially help encourage more 'functional' global custom blocks (due to the fact that the stage can't move) which I think is an important part of learning to code.

**Comment by haverdude** [comment]
I'm sorry for stirring the pot this vigorously, but the reason I posted was because I actually had to use Scratch to help my son who was working on a high school computer science project.

As someone who writes software for a living, what bothered me was that IMHO, if you use Scratch as a  teaching tool, because of it's limitations, I felt (and still do) that it was teaching bad practices, and more importantly, a flawed way of thinking.

I'm ok with the "thinking algorithmically", and I'm even ok with starting by duplicating code.  However, as my son and I got deeper into his project, it became clear very quickly that we were fighting the tool

I'm sensitive to this as I started in high school learning Basic on a TRS-80 (which was brand new).  The teacher had only taken a 6 week course in programming over the summer and I ended up "knowing" more than he did by the end of the course.  When I got to college, I had to UNLEARN all the stuff I thought I knew - because I had learned on my own, and had taught myself a lot of bad practices.  

However, those bad practices that I had to throw away seem very similar to what Scratch makes you do.

So, I guess I was just expressing my frustration that something that could be great (and in many ways IS) is marred by not providing a solid foundation for learning.  Yes, you can get a lot done in Scratch, but it's going to be laborious and it's not going to be as good as it could be, and if you learn on Scratch, that's going to be your universe - your first truth as it were.

I just think that first truth should be something more easily carried forward.

**Comment by bobbybee** [comment]
@haverdude Scratch is meant for kids younger than your son. Specifically, it's meant for people who couldn't otherwise program for various reasons. These people -- usually young kids -- are not going to miss global procedures. It's an extra. 

I grew up with Scratch. I'm currently writing a compiler and a toy kernel. I can assure Scratch works just fine for its intended audience. And "relearning the paradigm" is absolutely okay. And something you're going to do anyway when you learn a Lisp.

**Comment by haverdude** [comment]
I agree about Lisp (we called it "Lots of Stupid Parentheses", back in the
day - they still teach this?), and yeah, I had to do the compiler thing
too.  Writing a kernel is fun - just ask Linus.

FWIW: I write UEFI BIOS code now (don't get me started about that) - but
did embedded systems for years, and wrote my own GUI when we were still
running on MSDOS, and a zillion Windows apps, so I've kind of gone all the
way around the block.

However, one thing Iearned over the years, is that software has a funny way
of being used in ways that you had never intended.  Witness my son's pre-AP
CS teacher assigning high school juniors a project in Scratch.

In her defense, however, supposedly kids of that age group are *just *aging
out of Scratch.



Source:
https://blogs.kent.ac.uk/mik/files/2010/08/alice-scratch-greenfoot-ages.png


What's funny about this is that I had introduced him to Alice (2, I think,
at the time), when he was eight.  He took to it right away, just using the
tutorials to get started.

I'm also a Raspberry Pi guy (we have half a dozen of these things around
here) and Scratch is one of the major applications that is used, especially
in a RPI-teaching environment.

It just would be nice if you didn't have "age out" of a programming tool.
How cool would it be if there was an environment that started out really
simple, but revealed it's capabilities as you learned, and then was finally
something that you could use to make flawless code - *for real.*

On Sun, Apr 24, 2016 at 3:36 PM, Alyssa Rosenzweig <notifications@github.com

**Comment by haverdude** [comment]
By the way, I think some of the suggestions that this discussion has
sparked are very worthy and should be looked into.  I'm hoping they just
don't get dismissed out of hand by the maintainers.

G

**Comment by LFP6** [comment]
@bobbybee Maybe I'm lacking some knowledge, but "it works fine for its intended audience" rubs me the wrong way. Please take a look at the topic I just posted: https://scratch.mit.edu/discuss/topic/195770/

**Comment by haverdude** [comment]
https://blockly-games.appspot.com/turtle?lang=en&level=10

**Comment by bobbybee** [comment]
@LFP6 I'm just saying, personally I never noticed Scratch was missing features, until I came back from other languages that had them. In that sense, it did its job of "bridge language" perfectly. It would of course be _nice_ to have many of these features -- I _am_ still in the community for a reason! -- but sometimes I need to remind myself that I am no longer the target audience.

I'm not saying Scratch is perfect. As it is, I _am_ the reporter of this issue. But the list of crucial features it needs is honestly quite short.

Also, look up Snap!.
