### ISSUE TITLE
Browser zoom level in Chrome breaks Costume/Sound context menu

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#800]
Verified on Windows 7 using Chrome.  From the project page, change the zoom level of the browser to greater than 110%, click on "see inside" to enter the editor and then right click on a costume.  No context menu appears.  The sound context menu still appears at this level but disappears at higher levels of browser zoom.

Exit the editor, set the zoom level back to 100%, go back into the editor and the context menus reappear.  

Exit the editor, set the zoom level to 80% and right-click on a costume or sound and the wrong context menu (the stage context menu) appears.

**Comment by kaschm** [comment]
FYI - per @sclements this is likely in the JS code

**Comment by sclements** [comment]
@rschamp I think the fix is here: https://github.com/LLK/scratchr2/blob/master/static/js/apps/project/scratch_app.js#L86

**Comment by 2jour** [comment]
https://github.com/LLK/scratch-flash/issues/957

**Comment by TheLogFather** [comment]
I should've added this info here, rather than 957...

I suspect this right-click problem with Chrome, though, is that it deals with the zoom in a very different way (to other browsers).

A great test of this is the project that demos issue #600: https://scratch.mit.edu/projects/86263314/

If you try it on a browser other than Chrome, you should find that the clone which detects the click-through depends on the zoom level - as you zoom in further, the detected click position moves further and further above and left of the ask prompt's blue tick button.

But on Chrome it doesn't - if you click in the same place in the tick button, you will always end up 'hitting' the same clone, no matter what zoom level you use. (This doesn't include fullscreen, which Scratch handles itself).

This suggests to me that Chrome is doing the zoom scaling itself, perhaps rather than telling Flash about it - or, at least, it's doing it in a very different way to FF, Safari, etc.
