### ISSUE TITLE
Not obvious how to make one block snap inside another block

### ISSUE THREAD

**Issue by mgatland** [LLK/scratch-flash#843]
Hi,

We're noticing a lot of our students struggle with snapping long sensing blocks into the hole in the if-then block.

The issue is that the block only snaps in place if the _left edge_ is lined up with the hole in the block below. However, this isn't obvious from the UI. (There's no visual indication that the left 50 pixels of the block are special.)

Attached is a mockup of some of the positions that our students typically try, which don't work.

I know this sounds like a super minor issue, but we're seeing it affect _most people_ i.e more than 50% of first time Scratch users. 

This may be a quirk of the way we teach; if so I'd love to know what we're missing! Our workaround is to say "You need to line up the left edge" and make a < left edge hand gesture until they get it. It isn't that bad but I wonder about people trying Scratch learning without a teacher present.

Suggested fixes:
1. Make it so when dragging a block, if your mouse cursor is over the hole then dropping the block snaps it into the hole - I think this would be intuitive but just a guess
OR
2. make it so hovering any part of the block over the hole makes it snap
OR
3. Visually indicate which part of the block is "snappable"

![2015-07-09 scratch snap struggle](https://cloud.githubusercontent.com/assets/364886/8594319/d3261cf8-2693-11e5-8dcd-bc90110273f0.png)

**Comment by TheLogFather** [comment]
I don't think it's a quirk of the way you teach, I think it's a genuine issue. I've spent a lot of time with Scratch, and even I find I forget for a moment when trying to drop things into slots.

It's something that's been on my mind for a while now, but I've failed to come to a good solution. -The most immediately obvious suggestion would be to have it so that if *any* part of a block is over an appropriate slot then it should be able to fall into it. But it doesn't take long to realise the futility of such a proposition (it's possible for longer blocks/expressions to be over multiple slots...)

The other suggestion would be if the part of the block with the cursor is over the slot. But one problem I find with that is that it would likely hide the 'highlight' that shows when you've got it right.

One feeling I have about it is that maybe there should be a degree of flexibility in Scratch deciding when and which slot is appropriate. What I mean is that there could be a lot more situations where it's really clear what the intention is, so Scratch could just go ahead and let you drop it in for such circumstances (e.g. I'd include all of your above cases). But if there is ambiguity about which slot is meant, then Scratch takes a more discerning route and makes a best guess which might be meant (e.g. the one nearest the cursor...?)

I don't know - I suspect it's one of those things that would need several possibilities trying out IRL, and so draw conclusions from that about what behaviour to implement.
(There's also the problem of changing something that's been used by so many, and behaving in a particular way for so long...)

**Comment by griffpatch** [comment]
The problem with having items 'drop' into slots behind the blocks being
dragged is that you wouldn't see where it was going to be dropped until
after you let go... because it would be behind the dragged block/s. The way
it works now means that you can always see where it's going, because it
overlaps the top left of the dragged block.

The only alternative i can think of off the top of my head would be that as
you mouse down (finger down) to drag a stack of blocks, the stack moves
smoothly to the right and down (complete with shadow to indicate drag) such
that your cursor ends up being at the top left of the dragged stack, and
then your cursor can indicate the where the stack will go (which is kinda
intuitive for mouse.. not sure about for touch.  It also means that if you
accidentally drag a stack out of place, your mouse it already in the right
location (or thereabouts) to put it back where it came from...

Griffpatch
