### ISSUE TITLE
[ACCEPTANCE] Define Custom Block

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#878]
OS: Windows 7 Mac osx 10.10.4

Browser: Chrome 43
Sever: staging v439

1. Create a custom block
2. Right click and click define on custom block

Expected : the define block is highlighted

Observed: I don't see anything highlighted

https://github.com/LLK/scratch-flash/pull/797

**Comment by 2jour** [comment]
Closing Issue since working as designed

**Comment by TheLogFather** [comment]
As it stands, it only 'jumps' to the define script in the scripts pane, rather than highlighting anything. -Try it with a more complicated project, where there are multiple define scripts that are spread over a wide area.

I have a more comprehensive highlighting system in the works which extends the current "show senders/receivers" for sprites: https://github.com/LLK/scratch-flash/pull/861

**Comment by TheLogFather** [comment]
Oh, just closed it, I see... :)

**Comment by 2jour** [comment]
Sorry about that @TheLogFather  :) 

Great feature by the way :)

**Comment by TheLogFather** [comment]
I'd agree, though, that it feels a bit odd that nothing happens in such a case...
I guess people would tend to use it only when the define script isn't already visible.
Still, I much prefer it with the highlighting... :)
