### ISSUE TITLE
Right click in the editor doesn't work - Chrome on Mac

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-flash#957]
On Mac 10.10.5 , Chrome Version 46.0.2490.86 - right clicking anywhere in the editor screen doesn't work - it's either showing nothing, or showing something unrelated.

It's working great in Safari, and also works for Carmelo (same system version, same browser version)

![image](https://cloud.githubusercontent.com/assets/15109618/11409321/1d3f9862-938d-11e5-9c24-863af06ab918.png)

![image](https://cloud.githubusercontent.com/assets/15109618/11409336/2d92534e-938d-11e5-9da2-aed46f1078b4.png)

**Comment by TheLogFather** [comment]
The problem is to do with the calculation of the position if you have the browser zoom level set to something other than 100%.

There are a number of things in the editor that tend not to work so well with zoom level not set to 100% (scroll-bars, etc.), so I'd recommend you just hit cmd-zero (before entering the editor) to reset it to 100%.

**Comment by 2jour** [comment]
Hi @morantsur, 
I am sorry you are having difficulty with the context menu. @TheLogFather is right. We have several issues that are related zoom.  

You can track the progress of this issue via  https://github.com/LLK/scratch-flash/issues/800 .

**Comment by griffpatch** [comment]
I don't think it's only to do with zoom... I find that on projects with
costumes that are much larger than the scratch player that the scripts pane
sometimes has issues with right click? I assumed it was something to do
with the large costume receiving the click as if it was not clipped by the
playing window? But I never really stopped to triage it.

**Comment by TheLogFather** [comment]
Yes, there are times in Stage3D mode where the right-click has issues (any costume, not just large).

But don't you find in those cases it's more that it doesn't really 'register' as a right-click, rather than, as happens above, a right-click in the wrong place? (In fact, I think I find it registers as if it's a normal click in that position, meaning it ends up running the script I tried to right-click.)

It's also very intermittent - I've not seen any clear pattern to understand what might cause it...

**Comment by TheLogFather** [comment]
I suspect this right-click problem with Chrome, though, is that it deals with the zoom in a very different way.

A great test of this is the project that demos issue #600: https://scratch.mit.edu/projects/86263314/

If you try it on a browser other than Chrome, you should find that the clone which detects the click-through depends on the zoom level - as you zoom in further, the detected click position moves further and further above and left of the ask prompt's blue tick button.

But on Chrome it doesn't - if you click in the same place in the tick button, you will always end up 'hitting' the same clone, no matter what zoom level you use. (This doesn't include fullscreen, which Scratch handles itself).

This suggests to me that Chrome is doing the zoom scaling itself, perhaps rather than telling Flash about it - or, at least, it's doing it in a very different way to FF, Safari, etc.
