### ISSUE TITLE
Set X Block -1-1-1-

### ISSUE THREAD

**Issue by 2jour** [LLK/scratch-flash#964]
OS: mac osx 10.10.5
Browser: Chrome 46

Server: 2.2.3 441
1. Open editor
2. in set x block input -1-1-1

Observed: accepts value and sets x to 0
Expected: Should not accept value since this is not a valid number

**Comment by TheLogFather** [comment]
There are lots of non-sensical strings it will allow you to type because numerical type inputs can include characters like minus sign, full stop, and "e" – so you can enter "...e---e...", for example. (And that "e" has certainly caused some confusion in the past.)

I wonder if it may be worth having some 'tighter' restrictions on the formatting of a typed numerical entry, so you can't type more than one "e", nor a minus anywhere but at the start and after an "e"?

Actually, one thing I've noticed before that is sort of 'missing' (but not strictly necessary) is the plus sign.
Entry of something like "1e-5" is allowed, but why not "1e+5"? (You can enter "1e5", though, so...)

**Comment by Jonathan50** [comment]
> Entry of something like "1e-5" is allowed, but why not "1e+5"? (You can enter "1e5", though, so...)

Because the `-` is used in negative numbers, but you don't use `+`&hellip;
