### ISSUE TITLE
Placeholders in RTL languages revert when changed and break the block

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-flash#984]
Reported by a user for hebrew: https://mitscratch.freshdesk.com/helpdesk/tickets/37151

If you use the sensing 'x position' of 'sprite 1' block, then switch into hebrew it looks correct:
'sprite 1'  של 'מיקום על ציר x'
But if you then select the sprite 1 pull down to select a different sprite (or even the same one) the text reverts to 'x-position'.
So you end up with something that says
'x-position in english' of  'x-position in hebrew'
And the block no longer works.

Simple project to demonstrate: https://scratch.mit.edu/projects/91831001/#editor

**Comment by cwillisf** [comment]
It turns out that the problem is a little crazier than it looked at first. I'm working on fixing it, but here's what's going on:

Suppose you start a new project in English, so you just have the stage (called "Stage") and the Scratch cat (called "Sprite1").

Now drag the "{x-position} of {Sprite1}" block out -- we'll call that the "get attribute" block for the purposes of this discussion.

Note that the "target" of the block is "Sprite1" even though that would normally not be allowed; if you click that drop-down menu it will only list "Stage" as an option. This is because getting the current sprite's attributes should be done with blocks in the Motion, Looks, and Sound categories.

Anyway, suppose you change the target to "Stage" on the "get attribute" block. The stage has a different list of attributes as compared to other sprites: for example, the stage doesn't have position attributes. Because of this, Scratch updates the attribute drop-down menu on the "get attribute" block: position, direction, and size are removed, and the word "costume" is replaced with the word "backdrop" in the menu.

The same attribute replacement process happens if another sprite is selected instead of the stage. When switching from one sprite to another the list of attributes ends up looking the same, but Scratch still rebuilds the menu.

Now, imagine the same sequence in an RTL language. Everything happens the same way up until selecting a new target for the "get attribute" block. Unfortunately, that last step -- the one which replaces the attribute list -- always modifies the left-most menu, even in RTL languages. This ends up replacing the target list with a list of attributes, which turns out not to work so well...
