### ISSUE TITLE
Discussion: Support for Scratch on more platforms than Flash

### ISSUE THREAD

**Issue by jgranick** [LLK/scratch-flash#994]
Hello,

We have helped bring Scratch to OpenFL, an open-source Flash implementation that works on Windows, Mac, Linux, iOS, Android, Flash and HTML5. In the interest of collaboration, I would like to help open a discussion about the core team interest in something like this. If you would prefer to have this discussion over email, or something more personal, please let me know.

Windows, Mac, Linux, iOS and Android run as native C++. For example, this means that the environment can run on the Raspberry Pi and other Linux systems. My kids were surprised when the Raspberry Pi ran only Scratch 1.

Increasingly, tablets are used by kids to access the internet, an HTML5 version of Scratch could allow for innovation beyond a PC or Mac desktop on the web.

Thanks! :shipit:

**Comment by jay4** [comment]
(Disclaimer: I'm not part of the LLK :stuck_out_tongue:)

There's an HTML5 **player** "in progress" [here](https://github.com/llk/scratch-html5). The reason why I so snarkily wrap that in quotes is because it hasn't had any commits in the last month and possibly longer.

There's an unofficial **editor** [here](https://github.com/nathan/pixie) but that hasn't had too much activity yet either. So I guess you could say we're long due for an HTML5 Scratch.

**Comment by CharlesAnifowose** [comment]
I would support this.

**Comment by thisandagain** [comment]
Hi @jgranick, we are actively working on the next version of Scratch that is designed to run on mobile devices and more platforms. Please stay tuned!

**Comment by CharlesAnifowose** [comment]
We have a partial implementation based on OpenFL. Would that be useful for anyone?

**Comment by fleskesvor** [comment]
@CharlesAnifowose That sounds very interesting. In what state is it feature wise compared to the official version?

**Comment by liam4** [comment]
See https://scratch.mit.edu/developers – read the section on Scratch Blocks. You can try out the current development version [here](https://llk.github.io/scratch-gui/).

**Comment by fleskesvor** [comment]
That looks (and works) great!
